druid/Dockerfile
druid/stackable/jmx/config.yaml

Install the Prometheus emitter extension.

Install Druid Prometheus extension

---

conf.py
druid/Dockerfile
hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
kafka/Dockerfile
nifi/Dockerfile
node-exporter/Dockerfile
opa/Dockerfile
prometheus/Dockerfile
spark/Dockerfile
trino/Dockerfile
ubi8-rust-builder/Dockerfile
zookeeper/Dockerfile

fixes https://github.com/stackabletech/docker-images/issues/25

Reduce image sizes

---

conf.py
druid/Dockerfile
druid/README.md

fixes https://github.com/stackabletech/docker-images/issues/43
Our log4j solution removed since it is fixed upstream.

Update druid version

---

conf.py

https://github.com/stackabletech/kafka-operator/issues/309

Add Kafka 3.1.0 image

---

conf.py
superset/CHANGELOG.md

- Add Superset 1.4.1
- Fix base image tag of Superset 1.3.2
- Add changelog
see stackabletech/superset-operator#109

Superset 1.4.1

---

superset/Dockerfile

Add python-ldap to superset

---

airflow/CHANGELOG.md
airflow/Dockerfile
conf.py

see stackabletech/airflow-operator#55

Add support for Airflow 2.2.4 with Python 3.9

---

conf.py
zookeeper/CHANGELOG.md

required by stackabletech/zookeeper-operator#444

Add ZooKeeper version 3.8.0

---

conf.py
trino/Dockerfile

part of https://github.com/stackabletech/trino-operator/issues/187

Added trino version 377 with new opa authorizer

---

airflow/CHANGELOG.md

Added missing label with release number.

updated changelog with release label

---

conf.py
superset/CHANGELOG.md
superset/Dockerfile
superset/constraints-1.3.2.txt
superset/constraints-1.4.1.txt

Base Superset image on the Red Hat UBI

---

ubi8-rust-builder/Dockerfile

Needed for https://github.com/stackabletech/secret-operator/pull/128

Add cmake to ubi8-rust-builder

---

superset/Dockerfile
superset/patches/0001-fix-Set-certificates-before-reconnecting-to-LDAP.patch

Apply the patch we PRed at Flask-Appbuilder: https://github.com/dpgaspar/Flask-AppBuilder/pull/1846

Add patch to fix Flask LDAP bug in Superset

---

conf.py
superset/CHANGELOG.md
superset/Dockerfile
superset/constraints-1.5.1.txt
superset/patches-1.3.2/0001-fix-Set-certificates-before-reconnecting-to-LDAP.patch
superset/patches-1.4.1/0001-fix-Set-certificates-before-reconnecting-to-LDAP.patch
superset/patches-1.5.1/0001-fix-Set-certificates-before-reconnecting-to-LDAP.patch

Add Superset 1.5.1

---

build_product_images.py

Had troubles with a parameter not correctly set

Change script error

---

conf.py
pyspark-k8s/CHANGELOG.md
pyspark-k8s/Dockerfile
spark-k8s/CHANGELOG.md
spark-k8s/Dockerfile

spark-k8s and pyspark-k8s: Add s3a and abfs libs

---

README.adoc
ubi8-rust-builder/Dockerfile

Forgot to delete the old repository

Remove duplicated baseos-repo

---

airflow/Dockerfile

Pull request for adding the Trino provider. I changed the ordering on docker cmds to reduce the size of the final image. Locally it was about 1 GB smaller.
Closes #168 
Closes #263

Updated with Trino dep + slimmed image size

---

airflow/CHANGELOG.md

Leftover of https://github.com/stackabletech/docker-images/pull/264

Add missing changelog entry

---

.github/workflows/product_images.yml

Add images vector and stackable-base to the GitHub action workflows

Add images vector and stackable-base to the GitHub action workflows

---

vector/Dockerfile

Fix hash of the stackable-base manifest list

Fix hash of the stackable-base manifest list

---

zookeeper/Dockerfile

Fix hash of the java-base manifest list

Fix hash of the java-base manifest list

---

conf.py

Needs https://github.com/stackabletech/trino-opa-authorizer/pull/22

Add Trino version 403

---

hadoop/CHANGELOG.md
hadoop/Dockerfile

for https://github.com/stackabletech/hdfs-operator/issues/288

Switched to vector java base image

---

hive/CHANGELOG.md
hive/Dockerfile

Update hive to java vector image

---

.github/workflows/release.yml

deactivate max-parallel setting

deactivate max-parallel setting

---

conf.py
opa/CHANGELOG.md
opa/Dockerfile

prerequisite for https://github.com/stackabletech/opa-operator/issues/410

Added vector to opa image

---

airflow/CHANGELOG.md
airflow/Dockerfile

A pre-requisite for https://github.com/stackabletech/airflow-operator/issues/177.

add git-sync functionality to airflow image

---

conf.py
druid/CHANGELOG.md
druid/Dockerfile
hive/Dockerfile

Prerequisite for stackabletech/druid-operator#364

Add jackson-dataformat-xml to the Druid image

---

CHANGELOG.md

Apparently this was missed in #338.

Add krb5 to changelog

---

CHANGELOG.md
image_tools/conf.py
nifi/CHANGELOG.md

part of https://github.com/stackabletech/nifi-operator/issues/403
versions according to https://github.com/stackabletech/issues/issues/375

Added nifi versions 1.20.0, 1.21.0

---

trino/CHANGELOG.md
trino/Dockerfile

Needed for https://github.com/stackabletech/trino-operator/issues/401

trino: Add htpasswd tool

---

image_tools/conf.py
superset/CHANGELOG.md
superset/Dockerfile

Needed for https://github.com/stackabletech/superset-operator/issues/342

feat[superset]: Add AuthLib lib, needed for OAuth integration

---

ubi8-rust-builder/Dockerfile

to get support for Cargo workspace inheritance

Update to cargo-cyclonedx 0.3.8

---

vector/Dockerfile
vector/README.md
vector/upload_new_vector_version.sh

- Script to upload new Vector versions to Nexus
- Comments & README

Minor vector improvements

---

java-base/CHANGELOG.md
java-base/Dockerfile

Nightly tests failed because of this
```[tasklist]
```

fix(java-base): Add needed tzdata-java package

---

.github/workflows/dev.yaml
.github/workflows/release.yml

Fixes https://github.com/stackabletech/docker-images/issues/414
Product images are automatically signed "keyless" using cosign, after they were pushed.

Sign container images

---

airflow/Dockerfile
hadoop/Dockerfile

This should fail the build if a download fails

Add "--fail" to curl commands

---

CHANGELOG.md
docker-images.iml
image_tools/conf.py
java-base/Dockerfile

Part of https://github.com/stackabletech/issues/issues/359
**NOTE:** This PR removes the properties that we appended to the security file. This means that the default properties remain unchanged (currently 10 secs for the negative cache and 30 secs for the positive one)
```[tasklist]
```

Remove Java DNS security props.

---

stackable-base/Dockerfile

Explicitly set stackable user home directory to /stackable in base image

---

testing-tools/Dockerfile

testing-tools: Add unzip package

---

CHANGELOG.md
testing-tools/Dockerfile

testing-tools: Add java package

---

CHANGELOG.md
testing-tools/Dockerfile

fix: testing-tools image build

---

CHANGELOG.md
conf.py
opa/Dockerfile
opa/upload_new_opa_version.sh

- added: 0.57.0
- removed: 0.27.1, 0.28.0, 0.37.2, 0.41.0, 0.45.0
- added new version upload script
```[tasklist]
```

Opa new version 0.57.0

---

.github/workflows/dev.yaml
.github/workflows/release.yml

- Disable dev image signing for testing

disable signing

---

.github/workflows/dev.yaml

Fix image signing (for dev images).
The signer steps only run if the bake command has actually produced any images.
```[tasklist]
```

bugfix: dev image signing

---

.github/workflows/release.yml

Update the release workflow to fix image signing similar to the dev flow.
```[tasklist]
```

fix: image signing during the release workflow

---

CHANGELOG.md
conf.py
superset/constraints-3.0.1.txt

Replace superset 3.0.0 with 3.0.1

---

hadoop/Dockerfile

Changed the curl callout for the topology provider.
```[tasklist]
```

fixed curl command

---

conf.py
testing-tools/Dockerfile
testing-tools/licenses/KEYCLOAK_LICENSE

Add Keycloak so that we don't need to download them in the demo and kuttl tests.
```[tasklist]
```

feat(testing-tools): add keycloak

---

CHANGELOG.md
nifi/Dockerfile

Part of https://github.com/stackabletech/nifi-operator/issues/489
```[tasklist]
```

feat(nifi): Add Apache Iceberg extensions

---

airflow/Dockerfile
superset/Dockerfile

fix: Adopt to new image mirror location

---

hello-world/Dockerfile

This PR just brings the hello world dockerfile in line with the other dockerfiles that have been revamped
```[tasklist]
```

Update Hello World Dockerfile to best practices

---

omid/Dockerfile

This is needed to compile Omid and seems to have been removed from the base image at some point.
```[tasklist]
```

Installs maven in omid builder image

---

CHANGELOG.md
conf.py

- added 3.9.1
- removed 3.8.1 (->3.8.3)
```[tasklist]
```

Add zookeeper 3.9.1

---

CHANGELOG.md
conf.py

- add version `3.5.2, `3.6.1`
- remove version `2.8.2` `3.4.0`, `3.5.1`
```[tasklist]
```

Add kafka 3.5.2, 3.6.1, remove 2.8.2, 3.4.0, 3.5.1

---

CHANGELOG.md
conf.py

- added version 3.4.2
- removed 3.4.0, 3.4.0-java17
```[tasklist]
```

Add version 3.4.2, remove 3.4.0, 3.4.0-java17

---

hadoop/Dockerfile

fix(hadoop): Move HDFS_UTILS to correct location in Dockerfile

---

CHANGELOG.md
conf.py

Replace trino 438 with 439

---

CHANGELOG.md
hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
java-base/Dockerfile

Add krb5-workstation to java-base

---

.github/workflows/dev.yaml
.github/workflows/release.yml

Copied and adjusted the SBOM part from Harbor, so that SBOMs are generated for and pushed to Nexus as well.
Successful run for airflow: https://github.com/stackabletech/docker-images/actions/runs/7991006454
I also validated and skimmed over the generated SBOM, looks good.

Push SBOMs to Nexus

---

conf.py

Bump hdfs-utils to 0.2.0

---

conf.py

bump: hdfs-utils to 0.2.1

---

CHANGELOG.md
ubi8-rust-builder/Dockerfile

Part of : https://github.com/stackabletech/issues/issues/538

Bump rust version

---

CHANGELOG.md
conf.py

Depends on : https://github.com/stackabletech/opa-bundle-builder/pull/16

bump opa bundle builder version

---

CHANGELOG.md
conf.py

440 contains row level filtering and masking, so we want that
```[tasklist]
```

feat(trino): Add Trino 440

---

kafka/Dockerfile
kafka/kubernetes.repo

Fixes broken build
```[tasklist]
```

fix(kakfa): Switch kubectl yum repo, as the old one is gone

---

.github/workflows/docker.yml
Makefile

Adding Harbour as image destination in addition to Nexus. Images and Manifest list will be pushed to Harbour.

Feature/ubi 8 rust builder multi arch Harbor

---

ubi8-rust-builder/Dockerfile

chore: bump rust version

---

ubi8-rust-builder/Dockerfile

chore: bump ubi8 version

---

.github/workflows/preflight.yaml

chore: bump preflight version

---

.github/workflows/dev.yaml
.github/workflows/docker.yml
.github/workflows/mirror.yaml
.github/workflows/release.yml

chore: bump docker actions

---

ubi8-rust-builder/Dockerfile

See #541.
```[tasklist]
```
<details>
```shell
```
</details>

Document rationale for protoc dependency

---

airflow/Dockerfile
stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

docs: Remove leftovers of UBI8

---

druid/upload_new_druid_version.sh
hadoop/upload_new_hadoop_version.sh
hbase/upload_new_hbase-operator-tools_version.sh
hbase/upload_new_hbase_version.sh
hbase/upload_new_phoenix_version.sh
hive/upload_new_hive_version.sh
hive/upload_new_postgres_driver_version.sh
kafka/upload_new_kafka_version.sh
nifi/upload_new_nifi_version.sh
opa/upload_new_opa_version.sh
spark-k8s/upload_new_spark_version.sh
trino-cli/upload_new_trino_version.sh
trino/upload_new_trino_storage_version.sh
trino/upload_new_trino_version.sh
upload_new_inotify-tools_version.sh
upload_new_jmx_exporter_version.sh
upload_new_kcat_version.sh
upload_new_protoc_version.sh
upload_new_statsd_exporter_version.sh
vector/upload_new_vector_version.sh
zookeeper/upload_new_zookeeper_version.sh

Add a script to upload a new protoc version
This also changes all scripts to include "set -euo pipefail" in a consistent way

Add a script to upload a new protoc version

---

opa/versions.py

```[tasklist]
```
<details>
```shell
```
</details>

Add OPA 0.66.0 and remove 0.57.0

---

CHANGELOG.md
kafka/versions.py

```[tasklist]
```
<details>
```shell
```
</details>

chore: Add Kafka 3.7.1 & 3.6.2

---

.github/actions/build/action.yml
.github/workflows/dev_airflow.yaml
.github/workflows/dev_druid.yaml
.github/workflows/dev_hadoop.yaml
.github/workflows/dev_hbase.yaml
.github/workflows/dev_hello-world.yaml
.github/workflows/dev_hive.yaml
.github/workflows/dev_java-base.yaml
.github/workflows/dev_java-devel.yaml
.github/workflows/dev_kafka-testing-tools.yaml
.github/workflows/dev_kafka.yaml
.github/workflows/dev_kcat.yaml
.github/workflows/dev_krb5.yaml
.github/workflows/dev_nifi.yaml
.github/workflows/dev_omid.yaml
.github/workflows/dev_opa.yaml
.github/workflows/dev_spark-k8s.yaml
.github/workflows/dev_stackable-base.yaml
.github/workflows/dev_superset.yaml
.github/workflows/dev_testing-tools.yaml
.github/workflows/dev_tools.yaml
.github/workflows/dev_trino-cli.yaml
.github/workflows/dev_trino.yaml
.github/workflows/dev_vector.yaml
.github/workflows/dev_zookeeper.yaml

```[tasklist]
```
<details>
```shell
```
</details>

fix: add build cache password action input

---

CHANGELOG.md
java-base/Dockerfile
java-base/versions.py
java-devel/Dockerfile
java-devel/versions.py
stackable-base/Dockerfile
trino-cli/Dockerfile
trino-cli/README.md
trino-cli/versions.py
trino/Dockerfile
trino/versions.py

```[tasklist]
```
<details>
```shell
```
</details>

Add Trino 451

---

CHANGELOG.md
nifi/stackable/patches/1.27.0/001-NIFI-no-zip-assembly-1.27.0.patch
nifi/stackable/patches/1.27.0/002-NIFI-no-host-header-check-1.27.0.patch
nifi/versions.py

```[tasklist]
```
<details>
```shell
```
</details>

Bump 1.26.0 to 1.27.0

---

.hadolint.yaml
stackable-base/Dockerfile

Move base image to new heredoc format
There are no functional changes

Move base image to new heredoc format

---

CHANGELOG.md

Missed in post-release step.
```[tasklist]
```
<details>
```shell
```
</details>

added release tag to changelog

---

.github/actions/publish-image/action.yml
.github/workflows/pr_pre-commit.yaml
.github/workflows/release.yml
opa/Dockerfile
spark-k8s/versions.py
stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

ci(release): Various workflow fixes

---

CHANGELOG.md
opa/versions.py

See: https://github.com/open-policy-agent/opa/releases/tag/v0.67.1
```[tasklist]
```

chore(opa): add 0.67.1

---

vector/upload_new_vector_version.sh
vector/versions.py

Part of https://github.com/stackabletech/issues/issues/626

chore(vector): bump Vector to 0.40.0

---

.github/workflows/preflight.yaml

Part of: https://github.com/stackabletech/issues/issues/631
```[tasklist]
```
<details>
```shell
```
</details>

chore(preflight): version 1.10.0

---

.github/ISSUE_TEMPLATE/update-base-java.md

fix(issue-templates): repair invalid tasklist

---

CHANGELOG.md
hbase/versions.py
omid/versions.py

part of https://github.com/stackabletech/docker-images/issues/834
```[tasklist]
```
<details>
```shell
```
</details>

chore(hbase-omid): versions for release 24.11

---

CHANGELOG.md
kafka/Dockerfile

chore: added cyrus-sasl-gssapi package for kafka/kreberos
```[tasklist]
```
<details>
```shell
```
</details>

chore: added cyrus-sasl-gssapi package for kafka/kreberos

---

.github/ISSUE_TEMPLATE/add-product.md

This adds a task which states that the badges in the README file need to be updated by running the appropriate script.

chore: Add task to add-product issue template

---

.github/workflows/dev_airflow.yaml
.github/workflows/dev_druid.yaml
.github/workflows/dev_hadoop.yaml
.github/workflows/dev_hbase.yaml
.github/workflows/dev_hello-world.yaml
.github/workflows/dev_hive.yaml
.github/workflows/dev_java-base.yaml
.github/workflows/dev_java-devel.yaml
.github/workflows/dev_kafka-testing-tools.yaml
.github/workflows/dev_kafka.yaml
.github/workflows/dev_kcat.yaml
.github/workflows/dev_krb5.yaml
.github/workflows/dev_nifi.yaml
.github/workflows/dev_omid.yaml
.github/workflows/dev_opa.yaml
.github/workflows/dev_spark-k8s.yaml
.github/workflows/dev_stackable-base.yaml
.github/workflows/dev_superset.yaml
.github/workflows/dev_testing-tools.yaml
.github/workflows/dev_tools.yaml
.github/workflows/dev_trino-cli.yaml
.github/workflows/dev_trino.yaml
.github/workflows/dev_vector.yaml
.github/workflows/dev_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
CHANGELOG.md

Fixes this error:
```
unexpected EOF while looking for matching `"'
```
See: https://github.com/stackabletech/actions/releases/tag/v0.0.7

ci: Bump stackabletech/actions to 0.0.7

---

CHANGELOG.md

Missed in #902
```[tasklist]
```
<details>
```shell
```
</details>

chore: Update changelog for ubiX-rust-builder rust toolchain

---

CHANGELOG.md

Part of https://github.com/stackabletech/issues/issues/647.
In future, will be automated by https://github.com/stackabletech/stackable-utils/issues/83.

chore: Update changelog for release 24.11

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.pre-commit-config.yaml

Cherry-picked from https://github.com/stackabletech/docker-images/pull/938

ci: Use correct version image index manifest tag

---

CHANGELOG.md

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release-24.11/24.11.1-rc1

---

CHANGELOG.md
tools/Dockerfile

Add the package util-linux-core to th tools image.
util-linux-core contains a basic set of Linux utilities, including the command logger which allows to enter messages into the system log.
Closes #796 
```[tasklist]
```
<details>
```shell
```
See the output of `bake` to …

feat (tools): Add the package util-linux-core

---

CHANGELOG.md
tools/Dockerfile

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

CHANGELOG.md

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1

---

CHANGELOG.md
opa/versions.py

Part of https://github.com/stackabletech/docker-images/issues/969
```[tasklist]
```
<details>
```shell
```
</details>

chore(opa): Bump to 1.0.0

---

java-base/versions.py
java-devel/versions.py

Part of https://github.com/stackabletech/docker-images/issues/964.
This is needed by at least Trino 469.

feat: Add Java 23

---

CHANGELOG.md
nix/sources.json
trino-cli/versions.py
trino-storage-connector/stackable/patches/470/0001-Add-cyclonedx-plugin.patch
trino-storage-connector/stackable/patches/470/patchable.toml
trino-storage-connector/versions.py
trino/stackable/patches/469/patchable.toml
trino/stackable/patches/470/0001-Add-cyclonedx-plugin.patch
trino/stackable/patches/470/patchable.toml
trino/versions.py

Part of https://github.com/stackabletech/docker-images/issues/971.
```[tasklist]
```
<details>
```shell
```
</details>

feat(trino): Replace 469 with 470

---

CHANGELOG.md

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.3.0-rc1

---

CHANGELOG.md

Update changelog tag (remove -rc1)

chore: Update changelog for 25.3.0

---

.github/workflows/reusable_build_image.yaml

Forgot to change the username for the manifest push in https://github.com/stackabletech/docker-images/pull/1088

fix: spark connect client Harbor credentials

---

CHANGELOG.md
stackable-base/Dockerfile

Updates containerdebug to 0.2.0.
Two major changes:
- Reduces frequency to every 30min
- Adds support for logging of open files limit

feat: Update containerdebug

---

rust/boil/src/build/mod.rs

Previously, `boil` ignored the docker child process error. Now, if the status code indicates a failure, `boil` will return an error as well.

fix(boil): Return error if docker child process fails

---

CHANGELOG.md
tools/boil-config.toml

Part of https://github.com/stackabletech/docker-images/issues/1232
Ran the `airflow-scheduled-job` demo as testing of the image
> [!NOTE]
<details>
```shell
boil build <IMAGE> --image-version <RELEASE_VERSION> --strip-architecture --load
kind load docker-image <MANIFEST_URI> --name=<name-of-your-test-cluster>
```
See the output of `boil` to retrieve the image manifest URI for `<MANIFEST_URI>`.
</details>

chore(tools): Update image for 25.11.0
