stackabletech/docker-images

airflow/Dockerfile
airflow/stackable/airflow_config.py
conf.py

- Airflow image for use with the airflow operator
- Uses a standard apache/airflow image with default versions (airflow + python) which can be overridden with the build script
- Defaults to airflow 2.2.3 and python 3.8 (some airflow components require at least python 3.7)
- Build tested locally with docker and helm

Airflow image

---

tools/Dockerfile

During the init phase of NiFi pods two additional tools are required to prepare the envionment:
- OpenSSL to prepare the keystore used for TLS
- bcrypt which is used to encrypt the admin password from a secret and insert it into the config file
As bcrypt tool I have chosen https://github.com/bitnami/bcrypt-cli mostly because it does not require python, node or any other heavyweight dependency.
I contemplated writing our own tool in Rust which would have been something like 50 lines, but saw no real benefit in this.

Adds installation of openssl and bcrypt to tools image.

---

build_product_images.py
conf.py
superset/Dockerfile

The base image tag for the Superset dockerfile is now parameterized and must be set in the configuration file for every Superset version.
The Stackable Superset image uses the official Superset image as base. The official images are not tagged properly. They use commit hashes as tags. The base image tag is not a dependency (like a Python or Scala version), so it should not be appended to the image tag. This is solved by prefixing the version item containing the base image tag with an underscore. Version items prefixed with an underscore are now only available as build arguments in the Dockerfile but not recognized as dependencies.
Closes #35

Parameterize the base image tag of the Superset dockerfile

---

superset/Dockerfile
superset/stackable/superset_config.py

Enable statsd logging in Superset.
This is needed for stackabletech/superset-operator#128.

Enable statsd logging in Superset

---

conf.py
hbase/CHANGELOG.md

- Add HBase 2.4.9
- Add changelog
- Linked to: https://github.com/stackabletech/hbase-operator/issues/120

hbase-image: add support for 2.4.9

---

conf.py
java-base/Dockerfile

Adds a Java base image (currently for 1.8.0 and 11) to be used in the operator images depending on java.
precondition for https://github.com/stackabletech/docker-images/issues/79

java-base image for 1.8.0 and 11

---

.github/workflows/reviewdog.yaml
superset/CHANGELOG.md
superset/Dockerfile
superset/stackable/superset_config.py

Static Superset configuration removed because it is now provided in a config map.
see stackabletech/superset-operator#173

Remove Superset configuration

---

superset/CHANGELOG.md
superset/Dockerfile

Set version label in Superset image
The version label was empty due to a missing `ARG` instruction in the Dockerfile.

Set version label in Superset image

---

superset/CHANGELOG.md
superset/Dockerfile

Add Python package pydruid to Superset image
This package contains a database driver which is necessary for Superset to connect to Apache Druid.

Add Python package pydruid to Superset image

---

hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
kafka/Dockerfile
nifi/Dockerfile
pyspark-k8s/Dockerfile
shared/log4shell_scanner
spark-k8s/Dockerfile
spark/Dockerfile
trino/Dockerfile
zookeeper/Dockerfile

I've added the arm64 version of log4shell_scanner and a wrapper script to run the correct version depending on the container architecture. The Java based images now build successfully on ARM.

Updated log4shell_scanner with support for aarch64 builds

---

build_product_images.py

This is tracked as part of the image/platform version anyway, and was a weird detail to require users to configure manually.
We could keep building the dep-tagged images as well as a fallback, but this doesn't seem worthwhile when they were never used anyway.
This applies to many of the ADR018 PRs already created, such as https://github.com/stackabletech/druid-operator/pull/238 and https://github.com/stackabletech/airflow-operator/pull/106.

Remove dependency versions from Docker image tags

---

java-base/Dockerfile
zookeeper/Dockerfile

This will be an issue for Kerberos, and has also caused problems for ZooKeeper's quorum TLS mode, which validates reverse DNS for ensemble peers.

Disable Java's DNS cache

---

hive/Dockerfile

Currently pushed as `docker.stackable.tech/teozkr/hive:2.3.9-abfs`

Hive: Add Azure/ABFS libraries

---

conf.py
druid/Dockerfile

- removed old druid versions (incompatible with java 11)
- switched to java 11, 
- removed druid prometheus emitter

Druid 0.23.0

---

.github/workflows/product_images.yml
.github/workflows/product_images_dispatch.yml
build_product_images.py

FIrst draft for cross-plattfrom compiling.
There are some braking changes for our github action. Giving the script -c will bring it back to normal but can be used with -a/--architecture arm64/amd64/... .  For our actions we can use the option -a to cross-compile. Be aware that not giving -a will result in --platform platform.machine(), so the native platform will be passed to docker. 
**Actual Issue:**
1. Java-Base and Tools can not build with --platform flag, we run into an error from redhead, feel free to try and comment your ideas. (**Solved**)
2. You can not give multiple platforms ant once like -a amd64, arm64 since buildx is not supporting multi-platform. That would be a next step if my approach is decent for now.

Cross-platform building

---

ubi8-rust-builder/Dockerfile

Add protoc to the ubi8-rust-builder image
The secret-operator depends on [`prost`](https://crates.io/crates/prost), a Protocol Buffers implementation for Rust. With version 0.11, `prost` will no longer provide a bundled `protoc`. Therefore `protoc` must be installed on the builder image. The Red Hat UBI 8 repositories do not provide `protoc`, so it is downloaded from the protobuf project on GitHub directly.

Add protoc to the ubi8-rust-builder image

---

conf.py
trino/CHANGELOG.md
trino/Dockerfile

Fixes https://github.com/stackabletech/trino-operator/issues/288
To build run
`python3 build_product_images.py -p java-base -i 0 -v 17 -a linux/amd64`
and
`python3 build_product_images.py -p trino -i 0.99.0 -v 395 -a linux/amd64`

trino: Added Trino version 395 (using Java 17)

---

airflow/Dockerfile
java-base/Dockerfile
opa/Dockerfile
pyspark-k8s/Dockerfile
spark-k8s/Dockerfile
superset/Dockerfile
tools/Dockerfile
ubi8-rust-builder/Dockerfile

Pin all versions with digests, checkout why renovate is not pinning digests on it's own. Until then we should have a solution and pin the current version to protect us from sudden changes.

Patch repo ubi 8 appstream and base os

---

druid/Dockerfile

The PR https://github.com/stackabletech/docker-images/pull/226 updated the druid java base image (and others) to 17. Druid only supports 11 for now. 
Configuring / disabling renovate should be another ticket.

Revert java base image to 11

---

CHANGELOG.md
conf.py
java-base/Dockerfile

Removed Java 1.8.0 support since no other products are using it.

Update java base image to latest ubi8 tag

---

hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
kafka/Dockerfile
nifi/Dockerfile
spark/Dockerfile
zookeeper/Dockerfile

I thought only Druid had to be reverted in https://github.com/stackabletech/docker-images/pull/234, but Hadoop etc is affected as well. So now just reverting the PR https://github.com/stackabletech/docker-images/pull/226 completely.

Revert all base image version (17 -> 11) merged with PR 226

---

airflow/Dockerfile
superset/Dockerfile

Now copying statsd-exporter from  its docker image to the main image for airflow and superset (hopefully multi arch compatible)
@Maleware can you confirm :) ?

Moved statsd-exporter to main image

---

hbase/CHANGELOG.md
hbase/Dockerfile

Use java-base:11-stackable0.3.0 which contains Vector, as base image for HBase.

Enable log aggregation in HBase

---

conf.py
hive/CHANGELOG.md
hive/Dockerfile

Added `jackson-dataformat-xml-x.x.x.jar` for Hive 2.3.9 and 3.1.3 log4j2 XmlFormat.
Do not merge before release 23.1 is done!

Prepare hive image for log4j2

---

nifi/CHANGELOG.md
nifi/Dockerfile

- Use vector base image
- Removed shadow-utils (in vector base image)
- Removed user and group add
Do not merge before release 23.1 is done!

Prepare NiFi image for logging

---

superset/CHANGELOG.md
superset/Dockerfile

setuptools pinned to version 66.1.1.
The setuptools version 67.0.0 and newer are not compatible with the supported Superset versions because parsing of the requirements is more strict and fails in Superset (see also pypa/setuptools#3790).
This fixes the following error when starting Superset:
```
Traceback (most recent call last):
File "/stackable/app/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3030, in _dep_map
return self.__dep_map
File "/stackable/app/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2826, in __getattr__
raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Fix broken Superset image 23.4.0-rc1

---

airflow/CHANGELOG.md
airflow/Dockerfile
vector/CHANGELOG.md
vector/Dockerfile

Add Vector to the Airflow images
Prerequisite for stackabletech/airflow-operator#213

Add Vector to the Airflow images

---

CHANGELOG.md
airflow/Dockerfile
build_product_images.py
conf.py
druid/Dockerfile
hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
java-base/Dockerfile
kafka/Dockerfile
nifi/Dockerfile
opa/Dockerfile
pyspark-k8s/Dockerfile
spark-k8s/Dockerfile
superset/Dockerfile
tools/Dockerfile
trino/Dockerfile
vector/Dockerfile
zookeeper/Dockerfile

This PR changes the build workflow to generate a Bakefile (https://docs.docker.com/build/bake/), which is then passed to a single `docker buildx` call. This allows us to refer to other Dockerfiles in the tree directly, rather than having to build every step in the dependency chain manually, updating all the image references in between.
Additionally, this lets Docker build and push multiple the whole tree in parallel, rather than building the images one by one.
~~Currently Airflow and Zookeeper (and their dependencies) have been updated to take advantage of local dependencies. Other images may not work without updating to the `docker/dockerfile:1` syntax.~~ All images have now been updated.

Build images using docker buildx bake

---

image_tools/conf.py
trino/CHANGELOG.md
trino/Dockerfile

- Added Trino version 414
- Make soft link for `jmx-exporter` e.g. `jmx_prometheus_javaagent-<version>.jar` -> `jmx_prometheus_javaagent.jar`
- Make `jmx-exporter` configurable in `conf.py`

Support Trino v414

---

image_tools/conf.py

So we get https://github.com/stackabletech/trino-opa-authorizer/issues/24 in

trino: Bump opa-authorizer version for Trino 414

---

airflow/Dockerfile

```[tasklist]
```
This enables us to e.g.
```
@task
def write_repos_to_s3(df: pandas.DataFrame):
staging_table_name =''.join(random.choice(string.ascii_lowercase) for i in range(32))
df.to_parquet(
f"s3://{S3_BUCKET}/staging/github/{staging_table_name}/repos.parquet",
storage_options={
"key": S3_ACCESS_KEY_ID,
"secret": S3_SECRET_ACCESS_KEY,
"client_kwargs": {'endpoint_url': S3_ENDPOINT}
}
)
return staging_table_name
```

feat(airflow): Add s3fs python package, needed for pandas S3 access

---

stackable-base/CHANGELOG.md
stackable-base/Dockerfile

using https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.8-1014&push_date=1687885725000&container-tabs=overview

Post release bump stackable-base ubi8-minimal

---

image_tools/conf.py
pyspark-k8s/CHANGELOG.md
pyspark-k8s/Dockerfile
spark-k8s/CHANGELOG.md
spark-k8s/Dockerfile

This fixes the missing tzdata-java package in 0.0.0-dev versions
Smoke test passed locally
```[tasklist]
```

fix(spark): Rework spark images to build on top of java-base image

---

airflow/CHANGELOG.md
airflow/Dockerfile
airflow/stackable/utils/run-airflow.sh

As per spark-k8s, the entrypoint script is wrapped in a runner script that evaluates/triggers the vector shutdown command via an environment variable (if set).
```[tasklist]
```

wrap entrypoint script to trigger pre/post hook commands

---

testing-tools/Dockerfile

Add kubectl to testing-tools image
kubectl will be used in the integration tests of the listener-operator to query the ingress addresses from the status of the Listeners.
This change was intentionally not added to the changelog because the testing-tools image is not released together with the Stackable Data Platform.
```[tasklist]
```

Add kubectl to testing-tools image

---

CHANGELOG.md
conf.py
vector/upload_new_vector_version.sh

Upgrade Vector to version 0.33.0
```[tasklist]
```

Upgrade Vector to version 0.33.0

---

CHANGELOG.md
conf.py
zookeeper/Dockerfile
zookeeper/upload_new_zookeeper_version.sh

- added 3.8.3
- removed 3.5.8, 3.6.3, 3.7.0, 3.8.0
- added nexus upload script
- removed openssl
- bump jmx-exporter to 0.20.0
```[tasklist]
```

ZooKeeper new version 3.8.3

---

CHANGELOG.md
conf.py
hadoop/Dockerfile

- added support for 3.2.4, 3.3.6
- removed support for 3.3.1, 3.3.3
- bumped jmx-exporter version to 0.20.0
```[tasklist]
```

New hadoop versions 3.2.4, 3.3.6

---

CHANGELOG.md
conf.py
hive/Dockerfile
hive/upload_new_hive_version.sh

- removed version 2.3.9
- bump jmx-exporter to 0.20.0 and add softlink
- add product version upload script
```[tasklist]
```

Consolidate hive image

---

CHANGELOG.md
conf.py
hbase/Dockerfile
hbase/licenses/HBASE_OPERATOR_TOOLS_LICENSE
hbase/stackable/bin/hbck2
hbase/upload_new_hbase-operator-tools_version.sh

Add hbase-operator-tools to the HBase image
```[tasklist]
```

Add hbase-operator-tools to the HBase image

---

CHANGELOG.md
hbase/Dockerfile

The ShellCheck comment turned the whole `RUN` argument into a comment and the paths in the hbck2 script were not substituted. This was the reason why no ShellCheck warning was emitted. Disabling the ShellCheck warning does not work in a Dockerfile, because there can be no separate line in the command which disables the ShellCheck, and inline comments with `` `# ...` `` and `$(: ...)` are not recognized by ShellCheck.
```[tasklist]
```

Fix path substitution in the hbck2 script

---

CHANGELOG.md
superset/Dockerfile

- Redhat has removed `tzdata` from the ubi-minimal images. See [here](https://www.reddit.com/r/redhat/comments/12maj9w/ubi_feedback/) and [here](https://bugzilla.redhat.com/show_bug.cgi?id=2223028). 
- Superset relies on [ZoneInfo](https://docs.python.org/3/library/zoneinfo.html#data-sources) to resolve time zones, and this is done by searching first under `TZPATH` (which is empty due to the point above) or for the tzdata python package.
- That package is added in this PR (airflow already has tzdata in its list of dependencies). 
```[tasklist]
```

fix: add tzdata to superset image

---

CHANGELOG.md
hive/Dockerfile

Fixes https://github.com/stackabletech/hive-operator/issues/170
Needs https://github.com/stackabletech/docker-images/pull/454
```[tasklist]
```

fix(hive): Update postgresql driver to 42.6.0

---

hbase/Dockerfile
hbase/stackable/patches/2.4.12/003-HBASE-25292-2.4.12.patch
hbase/stackable/patches/2.4.12/004-HBASE-25336-2.4.12.patch
hbase/stackable/patches/2.4.17/002-HBASE-25292-2.4.17.patch
hbase/stackable/patches/2.4.17/003-HBASE-25336-2.4.17.patch

This PR back-ports two fixes from HBase `2.5` to `2.4.12` and `2.4.17`.
Previously regions were stuck in transitioning when the regionservers were restarted e.g. by using `k rollout restart sts prod1-hbase-regionserver-default`.
These fixes are:
[HBASE-25292](https://issues.apache.org/jira/browse/HBASE-25292): Improve InetSocketAddress usage discipline
This patch fixed the regions stuck in transitioning.
[HBASE-25336](https://issues.apache.org/jira/browse/HBASE-25336): Use Address instead of InetSocketAddress in RpcClient implementation
This patch probably only effects hbase clients - but is needed as we offer HBase restservers.
Additionally we made sure that the two HBase images work against `23.7.0` and `0.0.0-dev` Stackable operators.
- Not all of these items are applicable to all PRs, …

Add HBASE-25292 and HBASE-25336 to HBase 2.4

---

conf.py

So far we pulled in [trino-storage](https://github.com/snowlift/trino-storage) from https://github.com/snowlift/trino-storage/releases/tag/v428.
This PR switched to a version with backports made in https://github.com/snowlift/trino-storage/pull/244, https://github.com/snowlift/trino-storage/pull/241 and https://github.com/snowlift/trino-storage/pull/240, as they are needed for a customer.
trino-storage 432 contains the fixes, so long-term we can get rid of a patched version again. 
CC @Maleware @soenkeliebau @maltesander  
```[tasklist]
```

feat(trino 428): Switch to patched storage connector

---

CHANGELOG.md
conf.py
hadoop/Dockerfile

This adds an extra jar file to the Hadoop image which contains an implementation of the `org.apache.hadoop.net.DNSToSwitchMapping` interface to generate rack IDs based on Kubernetes labels, so that HDFS knows the underlying Kubernetes architecture and can distribute blocks properly.
Related to https://github.com/stackabletech/hdfs-operator/issues/325
```[tasklist]
```

Add topology provider jar to Hadoop image.

---

CHANGELOG.md
stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile

Bump ubi8.8 to ubi8.9

---

CHANGELOG.md
ubi8-rust-builder/Dockerfile

Part of https://github.com/stackabletech/issues/issues/407
```[tasklist]
```

chore: Bump Rust to 1.74.0

---

hbase/stackable/patches/2.4.17/004-HBASE-27103-2.4.17.patch

This fixes a known hbase Issue for leveldbjni. Before, the arm64 build failed with
```[bash]
This product includes leveldbjni-all licensed under the The BSD 3-Clause License.
ERROR: Please check ^^^^^^^^^^^^ this License for acceptability here:
https://www.apache.org/legal/resolved
```
This was a part of https://github.com/stackabletech/issues/issues/483.
Epic: https://github.com/stackabletech/issues/issues/463
```[tasklist]
```

Patchfile for HBase arm builds

---

update_feature_tracker_db.sh

This PR is part of https://github.com/stackabletech/feature-tracker/issues/52 and depends on https://github.com/stackabletech/feature-tracker/pull/53.
It adds a new script that updates the feature DB for a given release (version).
For example, after release version 23.11.0, the database can be updated with:
```
./update_feature_tracker_db.sh 2023-11 23.11.0
```
```[tasklist]
```

Add release components (product images) to the feature DB

---

CHANGELOG.md
conf.py
opa/upload_new_opa_version.sh

We need opa >= 0.59.0 to be able to write [Rego v1](https://github.com/open-policy-agent/opa/releases/tag/v0.59.0).
In our supported product versions we planned to support 0.61.0 anyway, this just pulls the new version a few days early to make our lives easier at other places
```[tasklist]
```

feat(opa): Add version 0.61.0

---

CHANGELOG.md
ubi8-rust-builder/Dockerfile

Bump the default rust toolchain to 1.75.0
```[tasklist]
```

chore: Bump Rust to 1.75.0

---

CHANGELOG.md
hadoop/stackable/patches/3.3.4/002-datanode-registration-override-3.3.4.patch
hadoop/stackable/patches/3.3.6/002-datanode-registration-override-3.3.6.patch

Fixes https://github.com/stackabletech/hdfs-operator/issues/468, fixes https://github.com/stackabletech/hdfs-operator/issues/467
This changes the datanode identity from the pod hostname to the IP address. This fixes both WebHDFS and the broken datanode dashboard in the namenode web UI.
```[tasklist]
```

hadoop: Always use registered hostname

---

CHANGELOG.md
conf.py
trino/Dockerfile

- Added trino 438. This requires a conditional statement to not download the extra OPA authorizer for this version.
- Removed OPA 0.51.0
- Add java-base 21
- Add vector 0.35.0
```[tasklist]
```

Add trino 438

---

CHANGELOG.md
conf.py

- added druid 28.0.1
```[tasklist]
```

Add druid 28.0.1

---

CHANGELOG.md
hadoop/stackable/patches/3.3.4/006-HDFS-17378-3.3.4.patch

Fixup of https://github.com/stackabletech/docker-images/pull/555
```[tasklist]
```

fix(hadoop): Fix patches for 3.3.4

---

CHANGELOG.md
conf.py
hadoop/Dockerfile

hadoop: upgrade topology provider to 0.2.0
Part of https://github.com/stackabletech/hdfs-operator/issues/325
```[tasklist]
```

hadoop: upgrade topology provider to 0.2.0

---

CHANGELOG.md
conf.py

- remove hbase version 2.4.12
- bump hbase_thirdparty (4.1.4 -> 4.1.5)
```[tasklist]
```

Remove hbase 2.4.12

---

CHANGELOG.md
conf.py
hadoop/Dockerfile

Depends on https://github.com/stackabletech/hdfs-group-mapper/pull/2
```[tasklist]
```

feat(hadoop): Add hdfs-utils

---

hadoop/Dockerfile

Previously you had to fiddle around using `HADOOP_CLASSPATH`.
I don't know if this is the right direction, feedback welcome!
```[tasklist]
```

fix(hadoop): Add hdfs-utils and topology-provider to classpath by default

---

CHANGELOG.md
conf.py
hadoop/Dockerfile

As decided on [Slack](https://stackable-workspace.slack.com/archives/C031A56R127/p1708412435743889). This ends the 3.2 release line
```[tasklist]
```

Remove hadoop version 3.2.4

---

conf.py

Needed to pull in https://github.com/stackabletech/hdfs-utils/pull/4
```[tasklist]
```

bump(hdfs): Bump to hdfs-utils 0.1.1

---

CHANGELOG.md
testing-tools/python/requirements.txt

Add pytest to testing tools

---

CHANGELOG.md
conf.py

bump hdfs-topology-provider to 0.3.0
```[tasklist]
```

hdfs: bump hdfs-topology-provider to 0.3.0

---

CHANGELOG.md
conf.py
druid/upload_new_druid_version.sh
hadoop/upload_new_hadoop_version.sh
hbase/upload_new_hbase-operator-tools_version.sh
hbase/upload_new_hbase_version.sh
hive/upload_new_hive_version.sh
hive/upload_new_postgres_driver_version.sh
kafka/upload_new_kafka_version.sh
nifi/upload_new_nifi_version.sh
spark-k8s/upload_new_spark_version.sh
zookeeper/upload_new_zookeeper_version.sh

For https://github.com/orgs/stackabletech/discussions/42
```[tasklist]
```

feat(spark): Add support for 3.5.1

---

CHANGELOG.md
conf.py

After discussion around pulling in the latest product releases right before a Stackable release, I have restored the previous (and unreleased) versions of Airflow and Zookeeper.

revert: new Zookeeper and Airflow versions

---

CHANGELOG.md
conf.py

**Important: Storage connector not uploaded to nexus yet. DO NOT MERGE YET!**
- replace trino 440 with 442
- bump trino-cli from 440 to 442

Add trino and cli version 442

---

conf.py

Currently Trino 442 can't be build locally since it fails with
```
> [trino-442  7/16] RUN if [[ -n ${OPA_AUTHORIZER} ]] ; then         curl --fail -L [https://repo.stackable.tech/repository/packages/trino-opa-authorizer/trino-opa-authorizer-442-${OPA_AUTHORIZER}.tar.gz](https://repo.stackable.tech/repository/packages/trino-opa-authorizer/trino-opa-authorizer-442-$%7BOPA_AUTHORIZER%7D.tar.gz) | tar -xzC /stackable/trino-server/plugin ;     fi:
0.085 /bin/bash: OPA_AUTHORIZER: unbound variable
------
Dockerfile:44
--------------------
43 |     # TODO: remove the following RUN statement once Trino versions 414 and 428 are removed
44 | >>> RUN if [[ -n ${OPA_AUTHORIZER} ]] ; then \
45 | >>>         curl --fail -L [https://repo.stackable.tech/repository/packages/trino-opa-authorizer/trino-opa- …
```

Setting opa authorizer to

---

.github/pull_request_template.md

```[tasklist]
```
<details>
```shell
./build_product_images.py --product <product> --image_version <stackable-image-version>
```
See the output of `build_product_images.py` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

fix(pr template): mention bake instead of the now defunct build_product_images.py

---

CHANGELOG.md
superset/Dockerfile

Now all Superset versions build on the Ampere server :rocket: 
```[tasklist]
```
<details>
```shell
```
</details>

fix(arm): Let Superset 3.1.0 build on ARM

---

CHANGELOG.md
airflow/Dockerfile

Now all Airflow versions build on the Ampere server 🚀
```[tasklist]
```
<details>
```shell
```
</details>

fix(arm): Let Airflow 2.8.x and 2.9.x build on ARM

---

CHANGELOG.md
testing-tools/Dockerfile

The manifest list wasn't tagged properly. This PR corrects it to the appropriate sha.
```[tasklist]
```
<details>
```shell
```
</details>

Update python bullseye to multi architecture manifest list

---

CHANGELOG.md
hive/stackable/patches/3.1.3/002-HIVE-21939-protoc-2.5.0-dependence-has-broken-buildi.patch

Cherry-picking https://issues.apache.org/jira/browse/HIVE-21939 from https://github.com/apache/hive/commit/2baf21bb55fcf33d8522444c78a8d8cab60e7415
```[tasklist]
```
<details>
```shell
``` …

fix(hive): Fix build on ARM by back-porting HIVE-21939

---

CHANGELOG.md
conf.py
hive/Dockerfile

Should fix broken tests introduced in https://github.com/stackabletech/docker-images/pull/581
To sum this up for the suits:
* We used to ship the pre-built Hive binary in a container with java 11 runtime and everything worked (this was presumably built on java 8 )
* After building ourselves from source (with java 8 ) we switched the java runtime in the container from 11 to 8 and some weird tls stuff broker
* Switching back to 11 in the container fixes it
The log of the failing TLS access to MinIO is attached
[hive-metastore-default-0.log](https://github.com/stackabletech/docker-images/files/14988211/hive-metastore-default-0.log)
See https://stackable-workspace.slack.com/archives/C031A5BEFS7/p1713185172557459 for details
- Not all of these items are applicable to all PRs, the author should …

fix(hive): Fix TLS problems by switching back to Java 11

---

.github/workflows/dev.yaml
.github/workflows/release.yml

Align resources with x86 runners
```[tasklist]
```
<details>
```shell
```
</details>

chore: Increase arm CI runner resources to 4 vCPU

---

CHANGELOG.md
ubi8-rust-builder/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/541
Tested using `secret-operator git:(main) ✗ docker build -f docker/Dockerfile .`
```[tasklist]
```
<details>
```shell
``` …

chore: Bump protoc to 26.1

---

.github/workflows/preflight.yaml
CHANGELOG.md

Part of stackabletech/issues#559.
chore: pass linux arch to check-container so that the correct image can be pulled when using manifest lists.
Tested with:
`gh workflow run --ref chore/use-arch-for-preflight preflight.yaml`
https://github.com/stackabletech/docker-images/actions/runs/8829927993
```[tasklist]
```
<details>
```shell …
```

chore: pass linux arch to check-container

---

ubi9-rust-builder/Dockerfile

Install krb5-devel which is needed since UBI9 for secret-operator
```
#13 92.00   [/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libgssapi-sys-0.3.0/build.rs:9:11] res = Ok(
#13 92.00       Output {
#13 92.00           status: ExitStatus(
#13 92.00               unix_wait_status(
#13 92.00                   0,
#13 92.00               ),
#13 92.00           ),
#13 92.00           stdout: "/usr/lib64/libgssapi_krb5.so.2\n/usr/lib64/libgssapi_krb5.so.2.2\n",
#13 92.00           stderr: "",
#13 92.00       },
#13 92.00   )
#13 92.00   src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found
#13 92.00   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libgssapi-sys-0.3.0/build.rs:80:10:
#13 92.00   failed to generate gssapi bindings: …
```

Install krb5-devel which is needed since UBI9 for secret-operator

---

kafka-testing-tools/licenses/KCAT_LICENSES
kafka/Dockerfile
kafka/licenses/KCAT_LICENSES
kafka/upload_new_kafka_version.sh

Supersedes https://github.com/stackabletech/docker-images/pull/608
- Separate everything into builder & final image including log4shell scanner
- Add kafka/bin and kcat to the PATH
- Add KCAT license files
```[tasklist]
```
<details>
```shell
```
See the output of `bake` to …

Rework Kafka image to build from source

---

CHANGELOG.md
conf.py

Bump opa-bundle-builder with updated dependencies from https://github.com/stackabletech/opa-bundle-builder/pull/20
```[tasklist]
```
<details>
```shell
```
</details>

chore: Bump opa-bundle-builder

---

CHANGELOG.md
hadoop/Dockerfile
hadoop/stackable/patches/3.3.4/007-snappy-cves-3.3.4.patch
hadoop/stackable/patches/3.3.6/007-snappy-cves-3.3.6.patch

This PR fixes the following CVEs for snappy-java (bumped from 1.1.8.2 to 1.1.10.4):
CVE-2023-34453
CVE-2023-34454
CVE-2023-43642
CVE-2023-34455
It also strips the image of jars that we do not need (yarn, mapreduce, minicluster modules, plus test/source jars).
```[tasklist]
```
<details>
```shell …
```

chore: hdfs - remove unnecessary jars and bump dependency versions to fix CVEs

---

CHANGELOG.md
nifi/Dockerfile
nifi/stackable/patches/1.21.0/001-NIFI-no-zip-assembly.patch
nifi/stackable/patches/1.23.2/001-NIFI-no-zip-assembly.patch
nifi/stackable/patches/1.25.0/001-NIFI-no-zip-assembly.patch
nifi/stackable/patches/apply_patches.sh

For NiFi version 1.21.0 and 1.23.2 the github runners do not have enough space and fail to build these images:
```
Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.0:install (default-install) on project nifi-toolkit-assembly: Failed to install artifact org.apache.nifi:nifi-toolkit-assembly:zip:bin:1.21.0: No space left on device -> [Help 1]
```
The nifi-assembly zips the resulting binaries which adds another ~1.3 GB but are not used in the main image since the unzipped binaries are copied over.
This PR patches the pom file to not zip the binaries in the end to save disk space.
- Please make sure all these things are …

Patch NiFi assembly to not zip binaries to save disk space

---

CHANGELOG.md
conf.py
hive/Dockerfile

fixes https://github.com/stackabletech/hive-operator/issues/468.
Recent changes to the hadoop image resulted in a missing logging dependency (jackson-module-jaxb-annotations was originally bundler with the hadoop yarn client): this PR adds the missing specific version.
Start-up scripts for hadoop functions check various env-vars, even if the associated modules are never run. To avoid errors with the initialisation of these scripts default values have been set where necessary.
Local testing with `repo: docker.stackable.tech/sandbox/yarnless-hive` :-
```
--- PASS: kuttl (1193.36s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_openshift-false_s3-use-tls-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (315.83s)
--- PASS: …
```

fix: add jaxb library no longer bundled with hadoop

---

nifi/Dockerfile

Due to java heap problems with NiFi 1.21.0 on arm runners, we continue to use the binaries for 1.21.0.
The builder step is kept. 
```[tasklist]
```
<details>
```shell
``` …

Use NiFi 1.21.0 binaries

---

CHANGELOG.md
conf.py
druid/Dockerfile
druid/upload_new_druid_version.sh

Successfully ran smoke test with some flakiness that seems to be uncorrelated to this PR.
```[tasklist]
```
<details>
```shell
```
</details>

feat: Build Druid from source

---

CHANGELOG.md
druid/Dockerfile

With the merge of https://github.com/stackabletech/docker-images/pull/684 integration tests started failing.
This is due to error message below.
Did not run the integration tests for this change as the images build forever and the fix seems straight forward.
```
2024-05-27T08:20:12,366 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Encountered exception in DETERMINE_PARTITIONS.
java.io.UncheckedIOException: /stackable/apache-druid-28.0.1/quickstart/tutorial
at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2135) ~[commons-io-2.11.0.jar:2.11.0]
at org.apache.commons.io.FileUtils.iterateFiles(FileUtils.java:1904) ~[commons-io-2.11.0.jar:2.11.0]
at org.apache.druid.data.input.impl.LocalInputSource.getDirectoryListingIterator(LocalInputSource.java: …
```

fix(druid): Re-add needed quickstart folder

---

druid/Dockerfile
druid/stackable/patches/26.0.0/001-remove-druid-ranger-security.patch
druid/stackable/patches/27.0.0/001-remove-druid-ranger-security.patch
druid/stackable/patches/28.0.1/001-remove-druid-ranger-security.patch
druid/stackable/patches/apply_patches.sh

- Stop building the `druid-ranger-security` module
- Remove `druid-ranger-security` from the maven profile `dist` using a patch 
```[tasklist]
```
<details>
```shell
```
</details>

Remove druid-ranger-security extension from Druid image

---

CHANGELOG.md
kafka/Dockerfile

This adds the jmx broker.config to the kafka builder image and adds a softlink for the kcat binary to the location the operator uses.
Kafka container did not come up due to:
```
kafka Caused by: java.io.FileNotFoundException: /stackable/jmx/broker.yaml (No such file or directory)
```
Kcat sidecar did not get ready due to wrong bin path, and did not output any logs...
```[tasklist]
```
<details>
```shell
bake --product <product> …
```

Fix integration tests - Copy jmx broker config to builder image

---

CHANGELOG.md
opa/stackable/bin/process-logs

Change log level input format for opa `process-logs` script to uppercase to make it more consistent with the format in the OpaCluster CRD.
```[tasklist]
```
<details>
```shell
``` …

chore: change loglevel input format for opa process-logs script to uppercase

---

.actionlint.yaml
.github/workflows/dev.yaml
.github/workflows/release.yml
.github/workflows/ubi-rust-builder.yml

Replaces BuildJet with UbiCloud arm runners.
```[tasklist]
```
<details>
```shell
```
</details>

Switching to ubicloud arm runner

---

CHANGELOG.md
stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

We use `cargo cyclonedx` to place the SBOM alongside the binary, similar to what we do with the operators
```[tasklist]
```
<details>
```shell
```
</details>

feat: Add config-utils to stackable-base

---

CHANGELOG.md
omid/Dockerfile

Required for: https://github.com/stackabletech/hbase-operator/pull/515
```[tasklist]
```
<details>
```shell
```
</details>

feat(omid): include examples to simplify testing

---

trino/Dockerfile

Drop RPM, clean up intermediate files, avoid some copying
Fixes #722
```[tasklist]
```
<details>
```shell
```
</details>

Slim down Trino build

---

CHANGELOG.md
druid/Dockerfile
hadoop/Dockerfile
hbase/Dockerfile
hive/Dockerfile
java-base/Dockerfile
java-devel/Dockerfile
kafka/Dockerfile
nifi/Dockerfile
omid/Dockerfile
spark-k8s/Dockerfile
trino/Dockerfile
zookeeper/Dockerfile

ENV variables are inherited by images if they come from a parent image. This ENV variable disables the Log4j feature that caused CVE-2021-4428 (Log4Shell). Even though this probably has been disabled everywhere already it doesn't hurt to set this variable

Move the Log4j ENV variable to the java-base image

---

stackable-base/Dockerfile

Needs https://github.com/stackabletech/config-utils/pull/9
```[tasklist]
```
<details>
```shell
```
</details>

chore: Bump config-utils to 0.2.0

---

.github/workflows/dev.yaml
.github/workflows/preflight.yaml
.github/workflows/release.yml
CHANGELOG.md
airflow/versions.py
conf.py
druid/versions.py
hadoop/versions.py
hbase/versions.py
hello-world/versions.py
hive/versions.py
java-base/versions.py
java-devel/versions.py
kafka-testing-tools/versions.py
kafka/versions.py
kcat/versions.py
krb5/versions.py
nifi/versions.py
omid/versions.py
opa/versions.py
spark-k8s/versions.py
stackable-base/versions.py
superset/versions.py
testing-tools/versions.py
tools/versions.py
trino-cli/versions.py
trino/versions.py
vector/versions.py
zookeeper/versions.py

- Update image-tools to 0.0.8 (to support importing python modules via conf.py)
- Move each products version list to a file in the product directory, and import it in the main configuration.
This will allow us to only build the relevant images based on the change paths (future PR).
```[tasklist]
```
<details>
```shell …
```

chore: move product versions into product directory in preparation for individual product build workflows

---

CHANGELOG.md
conf.py

Fix the hbase versions reference

fix: use correct hbase versions

---

druid/Dockerfile

Fix the ownership of the Druid directory in the Druid image
The ownership was changed from `root` to `stackable`.
The tests failed because `/stackable/apache-druid-${PRODUCT}/var/druid/metadata.db` could not be created due to the ownership. While it is debatable if this file should be stored in a directory below the application directory, all directories and files in `/stackable` should be owned by `stackable` nevertheless.
```[tasklist]
```
<details>
The image can be built and uploaded to the kind cluster with the …

Fix the ownership of the Druid directory in the Druid image

---

hadoop/Dockerfile
java-base/Dockerfile
java-devel/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

fix: Fix Hadoop build by re-installing EPEL

---

.github/actions/build/action.yml

This cleans up some space on the runner to be able to build products which produce a bunch of data during build. This action was present before, but accidentally removed in #733. This now re-adds the action to fix the larger failing builds.

fix(ci): Re-add free-disk-space action

---

.github/workflows/pr_pre-commit.yaml

Enable pre-commit checks on pull requests.
> [!NOTE]
> To avoid workflow failures, install pre-commit locally, and run `pre-commit install`.
> [!IMPORTANT]
> **nix-users**: install `ruff` before running `pre-commit`, otherwise it will download an incorrectly linked version.
```[tasklist]
```
<details>
```shell …
```

ci(pull-request): Enable pre-commit action

---

.github/ISSUE_TEMPLATE/pre-release.md
.github/workflows/pr_pre-commit.yaml
druid/versions.py

Part of https://github.com/stackabletech/issues/pull/602

chore: Add a pre-release issue template

---

CHANGELOG.md
airflow/Dockerfile
airflow/stackable/utils/entrypoint.sh

When starting a container from the Airflow image, the following error is shown:
```shell
$ docker run -ti -u 1000:0 --rm docker.stackable.tech/sandbox/airflow:2.9.2-stackable0.0.0-dev bash
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
...
```
The problem is that on UBI that path wrong and that the g++ package needs to be installed.
```[tasklist]
```
<details>
The image can be built and uploaded to the kind cluster with the …

fix(airflow): path to libstdc++.so

---

druid/Dockerfile
hbase/Dockerfile

We encountered errors when building multible product versions at the same time with for example
`bake -p omid -i 0.0.0-dev` 
This builds 1.1.0, 1.1.1 and 1.1.2 in parallel, all of which shared the cache volume with the name "maven".
When attempting to delete the cache there was a race condititon that caused the rm for the first container to finish to fail because after the rm the directory was not empty - other containers were still using it.
Error log:
```
70.37 [INFO] Omid ............................................... SUCCESS [  7.297 s]
70.37 [INFO] Common ............................................. SUCCESS [  8.764 s]
70.37 [INFO] State Machine ...................................... SUCCESS [  0.450 s]
70.37 [INFO] Commit Table ....................................... SUCCESS [ …
```

Adds variable to the name of build caches to enable parallel builds of multiple versions

---

.github/actions/publish-image/action.yml

The second invocation of `cosign attest` currently attaches the SBOM to the image in docker.stackable.tech instead of the one in oci.stackable.tech, because `IMAGE_NAME` was not overridden in that step.

Fix: Dev images SBOM attestation

---

.github/workflows/release.yml

This was missing in release, and NiFi (et al) can't build without it.

ci(release): Add free-disk-space action

---

.github/workflows/release.yml

As found during release.
```[tasklist]
```
<details>
```shell
```
</details>

Removing hardcoded arch from bake command

---

.github/workflows/release.yml
.scripts/enumerate-product-versions.py
conf.py

- The enumerate-product-versions.py would not work because it can't find the module "conf" since it was moved to the .scripts subfolder
- Changes the release workflow to fail when the enumerate script fails. It used to just swallow the error

Fix release workflow

---

spark-k8s/versions.py
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/operator-templating/issues/415

chore: Bump Rust to 1.80.0 in ubi8/9-rust-builder

---

.github/actions/publish-image/action.yml
.github/actions/publish-manifest/action.yml
.github/workflows/dev_airflow.yaml
.github/workflows/release.yml

- Revert bad `release.yml` workflow from #790.
- The digest is empty, even after push (works on my machine though).
- I have decided not to update it in this PR, as it can be improved when it uses the reusable actions. Mostly because some variable names were used that have different meanings, and it would be an easy place for errors to creep in.
- Revert bad `publish-image` action from #790.
- The digest is empty, even after push (works on my machine though).
- Revert debug change from #800
- Extract repo digest from structured data (for the `publish-image` action).
- It is only available after push
- Extract repo digest from structured data (for the `publish-manifest` action).
- It _might_ only be available after push
- Uses `docker buildx imagetools inspect` to get the digest. I checked …

ci(dev): Extract digests from structured output

---

airflow/versions.py
java-base/versions.py
opa/versions.py
spark-k8s/versions.py
superset/versions.py

Related to https://github.com/stackabletech/docker-images/pull/802, fixes the builds by pointing to the new Vector version

fix: updated versions.py files to use vector 0.40.0

---

stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/issues/issues/626
Changes for:
- stackable-base
- ubi8-rust-builder
- ubi9-rust-builder 
Change summary:
- Bump UBI base images
- Bump `RUST_DEFAULT_TOOLCHAIN_VERSION`
- Ignore `CARGO_CYCLONEDX_CRATE_VERSION` (pending #783)
- Ignore `CARGO_AUDITABLE_CRATE_VERSION` (no new version)
- Bump `PROTOC_VERSION`
- Ignore `CONFIG_UTILS_VERSION` (no new version)
- add comments to Dockerfiles to make bumps easier

chore(rust): Bump container and tool versions

---

tools/Dockerfile

Fixing architecture sensitivity of the tools image build.
Added `TARGETARCH` as variable and use it to pull correct `kubectl` binary
```[tasklist]
```
<details>
```shell
``` …

Fixing arch selection for kubectl

---

CHANGELOG.md
hbase/Dockerfile

A link is added to `/stackable/hbase/lib` that points to the Phoenix server jar file. It is assumed that that the jar file has the same version as the Phoenix source zip file.
This is not the case for Hbase 2.6 where the source file is called `phoenix-5.3.0-4afe457-src.tar.gz` but the artifact is called `phoenix-server-hbase-2.6-5.3.0-SNAPSHOT.jar` and it leads to `ClassNotFoundException` when trying to start the Phoenix server.
This fix changes the link to point to the more generic file that doesn't include the actual Phoenix version.
For the 2.4 images this is:
```shell
root@2051a2f8df93 /stackable/hbase-2.4.18 # ls -l /stackable/phoenix/
lrwxrwxrwx. 1 stackable stackable        34 Jun 11  2023 phoenix-server-hbase-2.4.jar -> phoenix-server-hbase-2.4-5.2.0.jar
...
```
While for the 2.6 …

fix(hbase): link to phoenix server jar

---

CHANGELOG.md
kafka/Dockerfile
kafka/kubernetes.repo
kafka/versions.py

Part of https://github.com/stackabletech/issues/issues/626
- Add `3.8.0`
- Remove `3.4.1`, `3.6.1`, `3.6.2`
```[tasklist]
```
<details>
```shell
```
</details>
Tests pass
```
--- …
```

chore(kafka): Add 3.8.0

---

airflow/versions.py
java-base/versions.py
opa/versions.py
spark-k8s/versions.py
superset/versions.py
vector/versions.py

Replaces #802 and #803.
> _Fixes a Vector v0.40.0 regression where the reduce transform would not group top level objects correctly._
_container build works_

chore(vector): Bump to 0.40.1

---

CHANGELOG.md
hadoop/Dockerfile
hive/Dockerfile
hive/stackable/patches/4.0.0/01-postgres-driver.patch
hive/stackable/patches/4.0.0/02-logging-dependencies.patch
hive/versions.py

Part of https://github.com/stackabletech/issues/issues/620
During this is noticed a minor problem with `schemaTool.sh` and created https://github.com/apache/hive/pull/5419 (already merged :) )
We did **not** bump misc dependencies as Hive 3.1.3 is doing (see https://stackable-workspace.slack.com/archives/C031A5BEFS7/p1725275085248519 for details) to keep this within the defined time box. We can always do that later on based on a CVE scan.
```[tasklist]
```
<details>
The image can be built and uploaded to the kind …

feat: Add Hive 4.0.0

---

.github/workflows/pr_pre-commit.yaml
.pre-commit-config.yaml
airflow/Dockerfile

Part of https://github.com/stackabletech/issues/issues/637
This fixes two things:
- Install the hadolint binary to be able to run the pre-commit hook
- Set the default language version of `node` to `system`. This fixes issues on NixOS systems.

fix(ci): Install hadolint in pre-commit workflow

---

trino/Dockerfile

Fix small problem with Dockerfile introduced in https://github.com/stackabletech/docker-images/pull/822
```[tasklist]
```
<details>
```shell
```
</details>

chore: fix trino dockerfile

---

.github/actions/publish-image/action.yml

Last thing needed for https://github.com/stackabletech/issues/issues/614
Changes:
- Update Syft to latest version
- Fix CycloneDX version to 1.5
- Enable Syft's `sbom-cataloger` to pick up the build-time generated SBOMs
- Use https://github.com/stackabletech/mergebom to merge the information found in the new SBOMs inside the images with the information found by Syft's other catalogers. More details about this can be found in Nuclino and in the comments of `mergebom`.

feat: Generate extended SBOMs

---

omid/Dockerfile

I was checking the failing builds, all errors seem to be caused by flakiness in external sources, except this error in the Omid Dockerfile which snuck in with the SBOM generation PR. Must have been a copy/paste error after I first tested the Omid build locally. I fixed it and retested the Omid build for 1.1.0 and 1.1.2 locally, both worked fine and the SBOMs are present.

fix: Omid Dockerfile typo

---

.github/actions/publish-image/action.yml

Fix for https://github.com/stackabletech/docker-images/pull/827
Sorry, I hope this is the last fix: I built mergebom as a container image first but then switched to building a binary and forgot to adapt the signature check in the GitHub action, so that it matches the new workflow name.
Tested the change locally, works:
```
curl -L -o mergebom https://repo.stackable.tech/repository/packages/mergebom/stable-x86_64
curl -L -o mergebom.bundle https://repo.stackable.tech/repository/packages/mergebom/stable-x86_64_signature.bundle
cosign verify-blob --certificate-identity 'https://github.com/stackabletech/mergebom/.github/workflows/build_binary.yaml@refs/heads/main' --certificate-oidc-issuer https://token.actions.githubusercontent.com --bundle mergebom.bundle mergebom
Verified OK
```

fix: mergebom cosign verification

---

.github/workflows/pr_pre-commit.yaml

```[tasklist]
```
<details>
```shell
```
</details>

chore(pre-commit): GH uses same hadolint version as local hook

---

.github/actions/publish-image/action.yml

The args to `jq` were not parsed correctly, which resulted in e.g.
```
...
"purl": "$purl",
...
```
in the final JSON of the SBOM.
I could not figure out how to concatenate the two args with `jq` (`$name` and `$description`) so I concatenated both variables with Shellscript into one arg for `jq`.

fix: jq arg parsing

---

CHANGELOG.md
hadoop/stackable/patches/3.3.4/009-HADOOP-18516-3.3.4.patch
hadoop/stackable/patches/3.3.6/009-HADOOP-18516-3.3.6.patch
hadoop/stackable/patches/3.4.0/006-HADOOP-18516-3.4.0.patch
stackable-base/Dockerfile

Backport "[HADOOP-18516](https://issues.apache.org/jira/browse/HADOOP-18516): Support Fixed SAS Token for ABFS Authentication"
The `FixedSASTokenProvider` is used when connecting to the Azure Data Lake Storage, see stackabletech/hbase-operator#539.
```[tasklist]
```
<details>
```shell …
```

feat(hadoop): Backport "HADOOP-18516: Support Fixed SAS Token for ABFS Authentication"

---

.github/ISSUE_TEMPLATE/update-base-java.md
.github/ISSUE_TEMPLATE/update-base-stackable.md
.github/ISSUE_TEMPLATE/update-base-ubi-rust-builders.md
.github/ISSUE_TEMPLATE/update-base-vector.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hbase-phoenix-omid.md
.github/ISSUE_TEMPLATE/update-product-hdfs.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-kafka.md
.github/ISSUE_TEMPLATE/update-product-nifi.md
.github/ISSUE_TEMPLATE/update-product-opa.md
.github/ISSUE_TEMPLATE/update-product-spark.md
.github/ISSUE_TEMPLATE/update-product-superset.md
.github/ISSUE_TEMPLATE/update-product-trino.md
.github/ISSUE_TEMPLATE/update-product-zookeeper.md

- Allow the release notes to be updated at the same time (and linking the PR) instead of commenting and adding a label.
- Hint to delete acceptance criteria which do not apply (so all checkboxes can be ticked in the issue).
- Remove release note acceptance criteria from base images where they don't apply.

chore(issue-templates): Improve acceptance critera

---

CHANGELOG.md
trino/Dockerfile

Part of https://github.com/stackabletech/trino-operator/issues/648
```[tasklist]
```
<details>
```shell
```
</details>

fix(trino): Correctly report Trino version

---

CHANGELOG.md
hadoop/stackable/patches/3.3.4/001-YARN-11527-3.3.4.patch
hadoop/stackable/patches/3.3.6/001-YARN-11527-3.3.6.patch
hadoop/stackable/patches/3.4.0/001-YARN-11527-3.4.0.patch
spark-k8s/Dockerfile
spark-k8s/stackable/hbase-connectors-patches/1.0.1/001-fix-protobuf-on-aarch64.patch
spark-k8s/stackable/hbase-connectors-patches/apply_patches.sh
spark-k8s/versions.py

Fix the build of the Spark HBase connector on aarch64.
For aarch64, the protoc artifact from com.github.os72 is used. The same was already done for Hive (https://github.com/stackabletech/docker-images/blob/24.7.0/hive/stackable/patches/3.1.3/002-HIVE-21939-3.1.3.patch).
The "Apache Hadoop YARN Application Catalog Webapp" required an update of the node version to 14.17.0.
The Hadoop version was changed from 3.3.4 to 3.3.6 because this version is used for the HBase image. This reduces the build time and the required disk space.
part of #870 
```[tasklist]
```
<details>
<summary>TIP: Running …

fix: Spark HBase connector on aarch64

---

spark-k8s/Dockerfile

Fix Dockerfile lint error
Fixed error:
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
```[tasklist]
```
<details>
```shell
```
</details>

fix(spark-k8s): Dockerfile lint error

---

airflow/Dockerfile

It'd warn about GIT_SYNC being possibly undefined. This is correct in theory, in practice however we always set it from the outside and defining it here could lead to version skew or another place to update versions.

Ignore Docker warning

---

airflow/Dockerfile
kafka/Dockerfile
kafka/stackable/patches/3.7.1/001-cyclonedx-plugin.patch
kafka/stackable/patches/3.8.0/001-cyclonedx-plugin.patch
kafka/stackable/patches/apply_patches.sh
opa/Dockerfile
statsd_exporter/Dockerfile

Fix needed for https://github.com/stackabletech/issues/issues/614
Changes:
- Changed some `RUN` commands to Heredoc
- Break circular dependencies in the Airflow SBOM by removing the dependencies from the providers on Airflow itself. For example, in the current SBOM, `apache-airflow-providers-smtp` depends on `apache-airflow` and `apache-airflow` depends on `apache-airflow-providers-smtp`. This causes the rendering of the dependency tree in SecObserve to fail.
- Create an SBOM for Kafka. It took a while to figure out how to not include all the integration tests in the SBOM, this was the only working solution I found.
- Generate build-time SBOMs for OPA and statsd_exporter. I had to create a dummy Git repo with a dummy commit that's tagged with the version of OPA / statsd_exporter, because …

feat: add missing build-time SBOMs

---

java-base/Dockerfile
java-devel/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

chore(java-bases): Use a pull-through cache to reduce build failures

---

ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/operator-rs/issues/898
Bump the ubiX rust-biulder images to Rust 1.81.0.
```[tasklist]
```
<details>
```shell
```
</details>

chore(ubi-rust-builder): Bump Rust toolchain to 1.81.0

---

.github/workflows/dev_airflow.yaml
.github/workflows/dev_druid.yaml
.github/workflows/dev_hadoop.yaml
.github/workflows/dev_hbase.yaml
.github/workflows/dev_hello-world.yaml
.github/workflows/dev_hive.yaml
.github/workflows/dev_java-base.yaml
.github/workflows/dev_java-devel.yaml
.github/workflows/dev_kafka-testing-tools.yaml
.github/workflows/dev_kafka.yaml
.github/workflows/dev_kcat.yaml
.github/workflows/dev_krb5.yaml
.github/workflows/dev_nifi.yaml
.github/workflows/dev_omid.yaml
.github/workflows/dev_opa.yaml
.github/workflows/dev_spark-k8s.yaml
.github/workflows/dev_stackable-base.yaml
.github/workflows/dev_superset.yaml
.github/workflows/dev_testing-tools.yaml
.github/workflows/dev_tools.yaml
.github/workflows/dev_trino-cli.yaml
.github/workflows/dev_trino.yaml
.github/workflows/dev_vector.yaml
.github/workflows/dev_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
CHANGELOG.md

This PR updates all `stackabletech` actions to 0.0.6.
This also fixes the issue encountered [here](https://github.com/stackabletech/docker-images/actions/runs/11443883437/job/31837551061#step:4:356).

ci: Bump stackabletech/actions to 0.0.6

---

.github/workflows/dev_airflow.yaml
.github/workflows/dev_druid.yaml
.github/workflows/dev_hadoop.yaml
.github/workflows/dev_hbase.yaml
.github/workflows/dev_hello-world.yaml
.github/workflows/dev_hive.yaml
.github/workflows/dev_java-base.yaml
.github/workflows/dev_java-devel.yaml
.github/workflows/dev_kafka-testing-tools.yaml
.github/workflows/dev_kafka.yaml
.github/workflows/dev_kcat.yaml
.github/workflows/dev_krb5.yaml
.github/workflows/dev_nifi.yaml
.github/workflows/dev_omid.yaml
.github/workflows/dev_opa.yaml
.github/workflows/dev_spark-k8s.yaml
.github/workflows/dev_stackable-base.yaml
.github/workflows/dev_superset.yaml
.github/workflows/dev_testing-tools.yaml
.github/workflows/dev_tools.yaml
.github/workflows/dev_trino-cli.yaml
.github/workflows/dev_trino.yaml
.github/workflows/dev_vector.yaml
.github/workflows/dev_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
CHANGELOG.md

Bump stackabletech/actions to [0.0.8](https://github.com/stackabletech/actions/releases/tag/v0.0.8).
This shaves off about 48 minutes of time across jobs using the free-disk-space action.
> [!CAUTION]
> Leave merging until after hours as it will consume the Github Actions runners for quite some time.

ci: Bump stackabletech/actions to 0.0.8

---

.github/workflows/dev_airflow.yaml
.github/workflows/dev_druid.yaml
.github/workflows/dev_hadoop.yaml
.github/workflows/dev_hbase.yaml
.github/workflows/dev_hello-world.yaml
.github/workflows/dev_hive.yaml
.github/workflows/dev_java-base.yaml
.github/workflows/dev_java-devel.yaml
.github/workflows/dev_kafka-testing-tools.yaml
.github/workflows/dev_kafka.yaml
.github/workflows/dev_kcat.yaml
.github/workflows/dev_krb5.yaml
.github/workflows/dev_nifi.yaml
.github/workflows/dev_omid.yaml
.github/workflows/dev_opa.yaml
.github/workflows/dev_spark-k8s.yaml
.github/workflows/dev_stackable-base.yaml
.github/workflows/dev_superset.yaml
.github/workflows/dev_testing-tools.yaml
.github/workflows/dev_tools.yaml
.github/workflows/dev_trino-cli.yaml
.github/workflows/dev_trino.yaml
.github/workflows/dev_vector.yaml
.github/workflows/dev_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
CHANGELOG.md

> [!IMPORTANT]
> This fixes the workflows which were broken in #907.
Bump stackabletech/actions to [0.1.0](https://github.com/stackabletech/actions/releases/tag/v0.1.0).
This requires the free-disk-space action to be run directly in the workflow instead of being part of the build actions. See https://github.com/stackabletech/actions/pull/14.
```[tasklist]
```
<details>
```shell
bake --product <product> --image-version …
```

ci: Bump stackabletech/actions to 0.1.0

---

hbase/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

fix: hbase-entrypoint.sh chmod arg

---

CHANGELOG.md
tools/Dockerfile
tools/versions.py

Part of: <https://github.com/stackabletech/issues/issues/644>
This image is used to deploy the secret and listener ops in OLM environments.
`yq` is needed to manipulate the OLM manifests in order to append user defined tolerations and environment variables.
```[tasklist]
```
<details>
```shell …
```

feat: install yq in tools image

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/preflight.yaml
.github/workflows/ubi-rust-builder.yml

Add a job at the end of each workflow which only runs on failure to send a slack notitification.
<details>
<summary>Considerations</summary>
We had the following four options to choose from:
1. Manually create threads per workflow, and hard code thread ids into each workflow.
- Continuous log of build successes/failures along with relevant conversations.
- Main thread stays clean.
2. _Be smat_ and get a thread-id from a cached artifact, and if it doesn't exist, create a new one.
- Same as the first option, but without all the manual work. Good for adding new workflows.
3. Create a thread per workflow run (begin workflow, build, manifest, done)
4. Only message on failure (higher signal-to-noise, people might be happy to receive alerts for it since each would require action)
We opted for …

ci: Add failure notifications to workflows

---

.github/workflows/build_spark-k8s.yaml

Spark now depends on HBase and should be rebuilt automatically as well.

Spark now depends on HBase and should be rebuilt automatically as well

---

hbase/stackable/patches/2.6.0/06-CVE-2024-36114-bump-aircompressor-0-27.patch

This **should** fix the HBase 2.6.0 build errors.
```[tasklist]
```
<details>
```shell
```
</details>

Base aircompressor 0.27 patch diff on previous patches

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml

Remove redundant usages of the free-disk-space action found by @Techassi during the 24.11 release builds.

ci: remove redundant usages of the free-disk-space action

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.pre-commit-config.yaml

Part of https://github.com/stackabletech/issues/issues/647
Fixes the invalid version in the image index manifest tag.

ci: Use correct version image index manifest tag

---

CHANGELOG.md
nifi/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

Add NiFi hadoop Azure and GCP libraries

---

CHANGELOG.md
hbase/stackable/patches/phoenix/5.2.0/02-CVE-2023-34455-update-snappy-version.patch
hbase/stackable/patches/phoenix/5.2.0/series

Part of: https://github.com/stackabletech/vulnerabilities/issues/558
:green_circle: CI https://testing.stackable.tech/job/hbase-operator-it-custom/35/
Trivy scan shows the CVE is not present anymore.
```[tasklist]
```
<details>
```shell
```
See the output of `bake` to …

fix(hbase): CVE-34455

---

ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/operator-templating/pull/469

chore(ubi-rust-builder): Bump Rust toolchain to 1.82.0

---

.github/workflows/pr_test_build_images.yaml

> [!NOTE]
> This is a _dummy_ workflow which will be completed in a separate PR.

ci: register a dummy test_build_images workflow

---

stackable-base/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

chore: bump rust version in stackable base image

---

CHANGELOG.md
kafka/Dockerfile
kafka/kubernetes.repo

Not needed anymore since https://github.com/stackabletech/kafka-operator/pull/443.
We could have removed back than already, but waited for 24.11 explicitly just to be sure.
```[tasklist]
```
<details>
```shell
``` …

chore(kafka): Remove kubectl

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
.github/workflows/preflight.yaml
.github/workflows/release.yml
.github/workflows/ubi-rust-builder.yml
CHANGELOG.md

The workflows were checked with https://github.com/woodruffw/zizmor to find various security related improvements.
The following lints were fixed:
- [artipacked](https://woodruffw.github.io/zizmor/audits/#artipacked)
- [template-injection](https://woodruffw.github.io/zizmor/audits/#template-injection)

ci: Fix static analysis errors

---

.github/workflows/build_airflow.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml

Stagger jobs between the following schedules (different hours every second day from the first or second of the month):
- `0 0 1/2 * *` <https://crontab.guru/#0_0_1/2_*_*>
- `0 1 1/2 * *` <https://crontab.guru/#0_1_1/2_*_*>
- `0 2 1/2 * *` <https://crontab.guru/#0_2_1/2_*_*>
- `0 0 2/2 * *` <https://crontab.guru/#0_0_2/2_*_*>
- `0 1 2/2 * *` <https://crontab.guru/#0_1_2/2_*_*>
- `0 2 2/2 * *` <https://crontab.guru/#0_2_2/2_*_*>
```
cron: '0 0 1/2 * *' # https://crontab.guru/#0_0_1/2_*_*
- build_airflow.yaml
- build_java-base.yaml
- build_nifi.yaml
- build_testing-tools.yaml
cron: '0 0 2/2 * *' # https://crontab.guru/#0_0_2/2_*_*
- build_hbase.yaml
- build_kafka.yaml
- build_spark-k8s.yaml
- build_trino.yaml
cron: '0 1 1/2 * *' # https://crontab.guru/#0_1_1/2_*_*
- build_druid.yaml
- …
```

ci(build): stagger the scheduled builds to ease load on external systems

---

CHANGELOG.md
nifi/Dockerfile

Since NiFi 2.0.0 PutIceberg Processor and services were removed, so including the `include-iceberg` profile does nothing. Additionally some modules were moved to optional build profiles, so we need to add `include-hadoop` to get `nifi-parquet-nar` for example.
This PR adds profiles depending on the NiFi version.
```[tasklist]
```
<details>
```shell
kind load …
```

fix(nifi): Activate "include-hadoop" profile for nifi 2.*

---

CHANGELOG.md
hadoop/Dockerfile
hadoop/stackable/jmx/datanode.yaml
hadoop/stackable/jmx/journalnode.yaml
hadoop/stackable/jmx/namenode.yaml

hadoop: Fix the JMX exporter configuration for metrics suffixed with `_total`, `_info` and `_created`.
The type of the metrics suffixed with `_total` is changed from GAUGE to COUNTER.
The names of the metrics suffixed with `_info` and `_created` are now appended with an additional `_`.
Fixes stackabletech/hdfs-operator#634
```[tasklist]
```
<details>
```shell
kind load …
```

fix(hadoop): Fix the JMX exporter configuration

---

airflow/Dockerfile

Follow-up to https://github.com/stackabletech/docker-images/pull/918

Change style of Airflow to be consistent with other Dockerfiles

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml

This is to fix the regularly failing maven builds.
See further detail and link to slack thread: https://github.com/stackabletech/actions/pull/28

ci: bump stackabletech/actions to 0.6.0 to remove the bake buildx --cache option from image builds

---

patchable.nu

Running patchable for the first time failed on my machine with the error:
```
fatal: not a git repository: '/home/voeti/stackable/docker-images/druid/patchable-work/worktree/26.0.0/.git'
```
It looks like `git rev-parse --git-dir` throws this error because the worktree directory is not present yet in my case.

fix: patchable worktree initialization

---

CHANGELOG.md
airflow/versions.py
java-base/versions.py
opa/versions.py
spark-k8s/versions.py
superset/versions.py
vector/versions.py

Following  https://github.com/stackabletech/docker-images/issues/967
Updated Vector to `0.43.1` in
- /vector
- /airflow
- /superset
- /java-base
- /java-devel
- /opa
- /spark-k8s
```[tasklist]
```
<details>
```shell
``` …

chore(vector): Bump to 0.43.1

---

CHANGELOG.md
druid/stackable/patches/30.0.0/02-prometheus-emitter-from-source.patch
druid/stackable/patches/30.0.0/10-cve-2023-34455-rm-snappy.patch

See: https://github.com/stackabletech/vulnerabilities/issues/558
```[tasklist]
```
<details>
```shell
```
</details>

fix(druid): CVE-2023-34455

---

.scripts/upload_new_jmx_exporter_version.sh

Reverts the `upload_new_jmx_exporter_version.sh` script from #687 (it was missed in #933).
[Slack discussion](https://stackable-workspace.slack.com/archives/C02FZ581UCD/p1738149918664689)

revert(script): Change JMX Exporter source upload back to Jar upload

---

.scripts/upload_new_jmx_exporter_version.sh

Correction from https://github.com/stackabletech/docker-images/pull/985.
The old location doesn't have the new Jar.
The script now also checks the sha256 sum before uploading.

fix(script): Download jmx_exporter jar and sha256 sum file from github

---

.gitignore
CHANGELOG.md
kafka/stackable/patches/3.7.2/0001-Add-cyclonedx-plugin.patch
kafka/stackable/patches/3.7.2/0002-Use-stackable-maven-mirror.patch
kafka/stackable/patches/3.7.2/patchable.toml
kafka/stackable/patches/3.9.0/0001-Add-cyclonedx-plugin.patch
kafka/stackable/patches/3.9.0/0002-Use-stackable-maven-mirror.patch
kafka/stackable/patches/3.9.0/patchable.toml
kafka/versions.py

Part of https://github.com/stackabletech/docker-images/issues/968.
- Add Kafka 3.9.0
- Bump Kafka 3.7.1 to 3.7.2
> [!NOTE]
> In both cases, patches were added via patchable.nu (experimental).
```[tasklist]
```
<details>
```shell
```
See the output of `bake` to retrieve the …

feat(kafka): Add 3.9.0, Bump 3.7.1 to 3.7.2

---

CHANGELOG.md
airflow/Dockerfile
airflow/versions.py

Fixes https://github.com/stackabletech/docker-images/issues/987
:green_circle: Tested with the gitsync integration test:
```
--- PASS: kuttl (563.83s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.9.2_openshift-false_executor-kubernetes (148.17s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.10.2_openshift-false_executor-celery (211.42s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.9.3_openshift-false_executor-kubernetes (167.46s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.9.2_openshift-false_executor-celery (206.06s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.9.3_openshift-false_executor-celery (195.18s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.10.2_openshift-fal …
```

chore: Update gitsync to v4.4.0

---

.github/ISSUE_TEMPLATE/update-base-java.md
.github/ISSUE_TEMPLATE/update-base-vector.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hbase-phoenix-omid.md
.github/ISSUE_TEMPLATE/update-product-hdfs.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-kafka.md
.github/ISSUE_TEMPLATE/update-product-nifi.md
.github/ISSUE_TEMPLATE/update-product-opa.md
.github/ISSUE_TEMPLATE/update-product-spark.md
.github/ISSUE_TEMPLATE/update-product-superset.md
.github/ISSUE_TEMPLATE/update-product-trino.md
.github/ISSUE_TEMPLATE/update-product-zookeeper.md
.github/workflows/preflight.yaml
.scripts/update_feature_tracker_db.sh
CHANGELOG.md
README.md

Part of https://github.com/stackabletech/infrastructure/issues/142
Updates registry references to oci
```[tasklist]
```
<details>
```shell
```
</details>

chore: update to oci references

---

CHANGELOG.md
kafka/stackable/patches/3.7.1/001-cyclonedx-plugin.patch
kafka/stackable/patches/3.7.1/002-use-stackable-repo.patch
kafka/stackable/patches/3.8.1/0001-Add-cyclonedx-plugin.patch
kafka/stackable/patches/3.8.1/0002-Use-stackable-maven-mirror.patch
kafka/stackable/patches/3.8.1/patchable.toml
kafka/versions.py

Part of https://github.com/stackabletech/docker-images/issues/968.
This PR corrects work done in https://github.com/stackabletech/docker-images/pull/988.
- Restore 3.7.1
- Replace 3.8.0 with 3.8.1.
- kafka 3.8.1 source uploaded to Nexus.
- Patches applied via patchable.nu (experimental)
> [!NOTE]
> Container image build tested via `bake kafka=3.8.1`.

fix(kafka): Restore version 3.7.1, bump 3.8.0 to 3.8.1

---

nifi/Dockerfile

```[tasklist]
```
<details>
```shell
```
</details>

docs(nifi): Document the needed for packages

---

spark-k8s/Dockerfile
spark-k8s/versions.py

Make Spark use our new LTS version of HBase.
Running the hbase-connector test failed for me, because the class `StaticLoggerBinder` could not be found. It seems like the Maven command in line 152 downloads the file to `/stackable/spark` instead of `/stackable/spark/jars`, even though it's running in that directory, but I guess Maven resolves "." to the directory that `pom.xml` is located in (which is `/stackable/spark`). That results in the `log4j-slf4j-impl` jar not being there at runtime. Once I fixed it, the test succeeded on my machine.
```[tasklist]
```
<details>
<summary>TIP: Running …

chore: bump hbase version used by spark / fix failing hbase connector test

---

stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/operator-templating/issues/484

chore: Bump Rust toolchain to 1.84.1

---

CHANGELOG.md
opa/Dockerfile
stackable-base/Dockerfile

Part of <https://github.com/stackabletech/operator-templating/issues/484>
The stackable-base image pulls in a bunch of Rust based projects (config-utils, containerdebug, opa-bundle-builder). Each of those projects (might) use a different toolchain from what we set as the default toolchain (1.84.1 as of #1012).
Since 1.28.0 (released on 2025-03-02), `rustup` will no longer automatically install the toolchain specified in `rust-toolchain.toml`. Instead, we manually need to run `rustup toolchain install` to install it before building.

fix: Install correct Rust toolchains for sub projects

---

druid/stackable/patches/31.0.1/0009-Update-FMPP-version.patch

The "Update FMPP" patch for Druid 31.0.1 creates an unnecessary `10-update-fmpp.patch` file (this was probably accidentally introduced when migrating the patches to the Patchable format). This currently causes Patchable to fail during checkout of Druid 31.0.1 (`Diff::from_buffer` is failing to parse the diff).
```[tasklist]
```
<details>
```shell …
```

fix: remove unnecessary file from druid 31 patch

---

CHANGELOG.md
hive/stackable/patches/4.0.0/0001-Include-Postgres-driver.patch
hive/stackable/patches/4.0.0/0002-Include-logging-dependencies.patch
hive/stackable/patches/4.0.0/0003-Add-CycloneDX-plugin.patch
hive/stackable/patches/4.0.0/0004-Fix-CVE-2024-36114.patch
hive/stackable/patches/4.0.0/patchable.toml
hive/versions.py

As discussed [here](https://github.com/stackabletech/demos/pull/173), Hive 4.0.1 removes functions that break python-iceberg.
```[tasklist]
```
<details>
```shell
```
</details>

fix: readd Hive 4.0.0

---

CHANGELOG.md
spark-k8s/Dockerfile

- removed log4shell check
- removed patches from final image
```
REPOSITORY                              TAG                                   IMAGE ID       CREATED              SIZE
oci.stackable.tech/sdp/spark-k8s        3.5.5-stackable25.3.0-reduced-size    b7343e448bbc   About a minute ago   1.64GB
oci.stackable.tech/sdp/spark-k8s        3.5.5-stackable25.3.0                 c09da49b3bfb   2 days ago           2GB
```

Fix: spark-k8s reduce image size

---

CHANGELOG.md
stackable-base/Dockerfile
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

This PR adds the `--locked` flag to the cargo install commands to use the same dependencies and versions as defined in the `Cargo.lock` file to prevent older builds to resolve to newer versions and consequently breaking the build. This needs to be cherry-picked into older release branches.
Example error when building nifi on `release-24.11` branch:
```
40.44 error: failed to compile `cargo-cyclonedx v0.5.5`, intermediate artifacts can be found at `/tmp/cargo-installrlShDo`.
40.44 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
40.44 
40.44 Caused by:
40.44   rustc 1.80.1 is not supported by the following packages:
40.44     litemap@0.7.5 requires rustc 1.81
40.44     zerofrom@0.1.6 requires rustc 1.81
40.44   Try re-running …
```

fix: Add `--locked` flag to cargo install commands

---

CHANGELOG.md
ubi8-rust-builder/Dockerfile
ubi9-rust-builder/Dockerfile

This updates:
- the Rust toolchain to 1.85.0
- cargo-cyclonedx to 0.5.7 and cargo-auditable to 0.6.6

chore(ubi8/9): Prepare images for Rust 2024 edition

---

.github/workflows/build_spark-connect-client.yaml
.scripts/update_readme_badges.sh
README.md

Part of https://github.com/stackabletech/spark-k8s-operator/issues/284
```[tasklist]
```
<details>
```shell
```
</details>

feat: add spark connect client to image build flows

---

CHANGELOG.md
opa/Dockerfile

```
REPOSITORY                                       TAG                                   IMAGE ID       CREATED             SIZE
oci.stackable.tech/sdp/opa                       1.0.1-stackable25.3.0-reduced-size    fe3a6374d0c6   2 minutes ago       417MB
oci.stackable.tech/sdp/opa                       1.0.1-stackable25.3.0                 9cf54f0be3b9   27 hours ago        477MB
```
- bundles artifacts in opa builder into /stackable/* to just copy the whole folder in the final image 
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in …

Fix: OPA reduce image size 

---

CHANGELOG.md
druid/Dockerfile

```
REPOSITORY                              TAG                                   IMAGE ID       CREATED          SIZE
oci.stackable.tech/sdp/druid            31.0.1-stackable25.3.0-reduced-size   f17d5ed72c07   58 seconds ago   1.19GB
oci.stackable.tech/sdp/druid            31.0.1-stackable25.3.0                818953ae9180   31 hours ago     1.85GB
```
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in the /stackable folder (example for nifi)
```
=> [nifi-2_2_0 final  7/10] RUN <<EOF (microdnf update...) …
```

Fix: druid reduce image size

---

CHANGELOG.md
airflow/Dockerfile
shared/checks/check-permissions-ownership.sh

No image size reduction, just consolidation.
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in the /stackable folder

Use check permissions script and consolidation

---

CHANGELOG.md
hive/Dockerfile

```
REPOSITORY                              TAG                                   IMAGE ID       CREATED         SIZE
oci.stackable.tech/sdp/hive             4.0.0-stackable25.3.0-reduced-size    1b28b0333195   4 minutes ago   1.67GB
oci.stackable.tech/sdp/hive             4.0.0-stackable25.3.0                 06c646169cff   2 days ago      1.75GB
```
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in the /stackable folder (example for nifi)
```
=> [nifi-2_2_0 final  7/10] RUN <<EOF (microdnf update...) …
```

Fix: hive reduce image size

---

CHANGELOG.md
kafka/Dockerfile
kcat/Dockerfile

```
REPOSITORY                              TAG                                   IMAGE ID       CREATED          SIZE
oci.stackable.tech/sdp/kafka            3.9.0-stackable25.3.0-reduced-size    427af0502953   12 minutes ago   708MB
oci.stackable.tech/sdp/kafka            3.9.0-stackable25.3.0                 51df3236caa8   2 days ago       847MB
```
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in the /stackable folder (example for nifi)
```
=> [nifi-2_2_0 final  7/10] RUN <<EOF (microdnf update...) …
```

Fix: kafka reduce image size

---

CHANGELOG.md
zookeeper/Dockerfile

```
REPOSITORY                               TAG                                   IMAGE ID       CREATED          SIZE
oci.stackable.tech/sdp/zookeeper         3.9.3-stackable25.3.0-reduced-size    0cdaed351a1c   5 minutes ago    553MB
oci.stackable.tech/sdp/zookeeper         3.9.3-stackable25.3.0                 c39102329a46   2 days ago       577MB
```
- removed log4shell check
- Uses check-permissions-ownership script to validate any wrong permissions / ownership in the /stackable folder (example for nifi)
```
=> [nifi-2_2_0 final  7/10] RUN <<EOF (microdnf update...) …
```

Fix: zookeeper reduce image size

---

.scripts/upload_new_async-profiler_version.sh
.scripts/upload_new_inotify-tools_version.sh
.scripts/upload_new_jmx_exporter_version.sh
.scripts/upload_new_kcat_version.sh
.scripts/upload_new_protoc_version.sh
.scripts/upload_new_tini_version.sh
druid/upload_new_druid_version.sh
hadoop/upload_new_hadoop_version.sh
hbase/upload_new_hbase-operator-tools_version.sh
hbase/upload_new_hbase_version.sh
hbase/upload_new_phoenix_version.sh
hive/upload_new_hive_version.sh
kafka/upload_new_kafka_version.sh
nifi/upload_new_nifi_version.sh
omid/upload_new_omid_version.sh
opa/upload_new_opa_version.sh
spark-k8s/upload_new_hbase-connector_version.sh
spark-k8s/upload_new_spark_version.sh
statsd_exporter/upload_new_statsd_exporter_version.sh
trino-cli/upload_new_trino_version.sh
trino-storage-connector/upload_new_trino_storage_connector_version.sh
trino/upload_new_trino_version.sh
vector/upload_new_vector_version.sh
zookeeper/upload_new_zookeeper_version.sh

> [!NOTE]
> This came out of the [25.3.0 Release Retro](https://github.com/stackabletech/issues/issues/694).
>
> I did not add a flag as was discussed in the retro, but I believe the help text for switching URLs is easy enough.
- Use fast download mirrors (help text is emitted so that the user can change the `BASE_DOWNLOAD_URL` to the archive URL for example.
- Add a download/upload progress-bar since this is run by people.
- Only emit GPG key warning/help if the verification failed.

chore(⏲): Use fast download mirrors

---

.github/ISSUE_TEMPLATE/add-product.md
.github/ISSUE_TEMPLATE/early-pre-release.md
.github/ISSUE_TEMPLATE/update-base-java.md
.github/ISSUE_TEMPLATE/update-base-stackable.md
.github/ISSUE_TEMPLATE/update-base-ubi-rust-builders.md
.github/ISSUE_TEMPLATE/update-base-vector.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hbase-phoenix-omid.md
.github/ISSUE_TEMPLATE/update-product-hdfs.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-kafka.md
.github/ISSUE_TEMPLATE/update-product-nifi.md
.github/ISSUE_TEMPLATE/update-product-opa.md
.github/ISSUE_TEMPLATE/update-product-spark.md
.github/ISSUE_TEMPLATE/update-product-superset.md
.github/ISSUE_TEMPLATE/update-product-trino.md
.github/ISSUE_TEMPLATE/update-product-zookeeper.md
.github/pull_request_template.md

> [!NOTE]
> This came out of the [25.3.0 Release Retro](https://github.com/stackabletech/issues/issues/694)
- Use YY.M.X placeholders for consistence across templates
- Remove deprecated `[tasklists]` :sob:
- Add missing tool update tasks for cyclonedx and auditable
```[tasklist]
```
<details>
```shell …
```

chore(⏲): Add missing tool update tasks to templates

---

kafka/stackable/patches/3.8.0/0001-Add-CycloneDX-plugin.patch
kafka/stackable/patches/3.8.0/0002-Change-Gradle-to-use-the-Nexus-Build-Repo.patch
kafka/stackable/patches/3.8.0/patchable.toml

Builds are failing since https://github.com/stackabletech/docker-images/pull/1032 because the Patchable config for Kafka 3.8.0 is missing

fix: add missing patchable config for Kafka 3.8.0

---

.github/pull_request_template.md

fix(pr-template): Fix the rendering of the list

---

.github/workflows/build_airflow.yaml
.github/workflows/build_druid.yaml
.github/workflows/build_hadoop.yaml
.github/workflows/build_hbase.yaml
.github/workflows/build_hello-world.yaml
.github/workflows/build_hive.yaml
.github/workflows/build_java-base.yaml
.github/workflows/build_java-devel.yaml
.github/workflows/build_kafka-testing-tools.yaml
.github/workflows/build_kafka.yaml
.github/workflows/build_kcat.yaml
.github/workflows/build_krb5.yaml
.github/workflows/build_nifi.yaml
.github/workflows/build_omid.yaml
.github/workflows/build_opa.yaml
.github/workflows/build_spark-connect-client.yaml
.github/workflows/build_spark-k8s.yaml
.github/workflows/build_stackable-base.yaml
.github/workflows/build_superset.yaml
.github/workflows/build_testing-tools.yaml
.github/workflows/build_tools.yaml
.github/workflows/build_trino-cli.yaml
.github/workflows/build_trino.yaml
.github/workflows/build_vector.yaml
.github/workflows/build_zookeeper.yaml
.github/workflows/reusable_build_image.yaml

> [!NOTE]
<details>
```shell
```
</details>

feat: make image namespace a workflow input (default sdp)

---

.github/workflows/build_spark-connect-client.yaml
.github/workflows/reusable_build_image.yaml

Makes the workflow use the correct credentials for the robot account with access to the "stackable" repo
Test run: https://github.com/stackabletech/docker-images/actions/runs/14832966758

fix: spark connect client Harbor credentials

---

CHANGELOG.md
java-base/versions.py
java-devel/versions.py

Part of https://github.com/stackabletech/docker-images/issues/1096.
> [!NOTE]
> This will be used by Trino 476 once it is released.
> See: https://github.com/stackabletech/docker-images/pull/1095
> [!NOTE]
<details>
```shell
```
See the output of `bake` to retrieve the image …

chore(java): Add JDK 24

---

CHANGELOG.md
airflow/versions.py
java-base/versions.py
opa/versions.py
spark-k8s/versions.py
superset/versions.py
vector/versions.py

Closes https://github.com/stackabletech/issues/issues/687.
Part of https://github.com/stackabletech/docker-images/issues/1085
- Bump vector to 0.46.1.
> [!NOTE]
<details>
```shell
``` …

chore(vector): Bump to 0.46.1

---

.github/workflows/mirror.yaml
CHANGELOG.md
opa/Dockerfile
opa/versions.py
stackable-devel/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/1084.
> [!NOTE]
<details>
```shell
```
</details>

chore(opa): Update versions ahead of 25.7.0

---

java-base/versions.py

Part of https://github.com/stackabletech/docker-images/issues/1085.
This was missed by https://github.com/stackabletech/docker-images/pull/1098 due to changes from https://github.com/stackabletech/docker-images/pull/1097 coming in and being missed during merge-conflict resolution.

fix: Bump vector to 0.46.1 for java-base:24

---

CHANGELOG.md
nifi/Dockerfile

Small fix-up of https://github.com/stackabletech/docker-images/pull/1060

fix(nifi): Delete correct intermediate folder

---

CHANGELOG.md
conf.py

_Part of https://github.com/stackabletech/issues/issues/645_
Change default user id and gid to the same ones we use in the operators themselves.
These are only the defaults that are used when a Pod does not specify their own `securityContext.runAsUser` or `runAsGroup`.
As of now all our operators do set these (and `fsGroup`) to 1000 and 0 respectively.
As the next step we want to remove that hardcoding so the default would then fall back to what we specify here.
Therefore I do believe that this PR should be a simple change with no downstream consequences until the PRs from https://github.com/stackabletech/issues/issues/651 are merged.
<details>
The image can be built and uploaded to the kind cluster with the …

Change default user id and gid

---

.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-superset.md

This came from https://github.com/stackabletech/airflow-operator/pull/625#issuecomment-2864302787
```
❯ fd required-external-components.adoc
airflow-operator/docs/modules/airflow/pages/required-external-components.adoc
druid-operator/docs/modules/druid/pages/required-external-components.adoc
hive-operator/docs/modules/hive/pages/required-external-components.adoc
superset-operator/docs/modules/superset/pages/required-external-components.adoc
```

chore(issue_template): Add reminder to update prereqs for select products

---

.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
.github/workflows/preflight.yaml
.github/workflows/reusable_build_image.yaml
.github/workflows/ubi-rust-builder.yml

This PR adjusts the reusable workflow to use the new `send-slack-notification` action. It also
- Bumps actions/checkout to 4.2.2
- Bumps stackabletech/actions to 0.8.1

ci: Use send-slack-notification action

---

CHANGELOG.md
conf.py

This reverts commit b4b5a33ff42df0b513ccc0efeab5ec96045e3d2b.
It turns out that all operators need to be adapted first because even though they do hardcode user id & gid 1000 that does cause problems. The reason is that they rely on a user with id 1000 to actually be there and it isn't.
I don't know what I was thinking to be honest.

Revert "Change default user id and gid (#916)"

---

.pre-commit-config.yaml

There are warnings in our pre-commit output because the pre-commit-hooks is outdated.
I updated all dependencies while I was at it.

chore: Update pre-commit dependencies

---

CHANGELOG.md
nifi/stackable/patches/2.4.0/0003-disable-host-port-validation-if-list-of-allowed-host.patch

Starting in NiFi 2.4.0 the host header validation has been replaced by host port validation: https://github.com/apache/nifi/pull/9680
This adds a patch that replaces `0002-Allow-bypassing-check-for-host-header.patch` which was used to turn host header validation off if the list of allowed hosts contained only `*`.
> [!NOTE]
<details>
```shell …
```

fix(nifi): Conditionally disable Host Port Validation in NiFi 2.4.0

---

trino/Dockerfile
trino/storage-connector/stackable/patches/451/0001-Add-CycloneDX-plugin.patch
trino/storage-connector/stackable/patches/455/0001-Add-CycloneDX-plugin.patch
trino/storage-connector/stackable/patches/470/0001-Add-CycloneDX-plugin.patch

We added the CycloneDX Plugin to the Trino storage plugin, but it didn't generate the SBOM, from the build log:
> Skipping CycloneDX goal, because module skips deploy
Also, we forgot to copy the SBOM to the final image.
This PR actually generates the SBOM and also copies it to the final image.
> [!NOTE]
<details>
```shell …
```

fix: trino storage plugin SBOM

---

CHANGELOG.md
hadoop/stackable/jmx/datanode.yaml
hadoop/stackable/jmx/journalnode.yaml
hadoop/stackable/jmx/namenode.yaml

Allow boolean metrics to be exported for HDFS.
If a value field is provided in the JMX exporter rules, then the value is parsed as Double (see https://github.com/prometheus/jmx_exporter/blob/1.2.0/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L699-L714).
If the value field is "not specified the scraped mBean value will be used." (see http://prometheus.github.io/jmx_exporter/1.2.0/http-mode/rules/). This seems to be the usual case anyway.
If the bean value is used, numbers and booleans are supported (see https://github.com/prometheus/jmx_exporter/blob/1.2.0/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L800-L811).
With this change, e.g. the metric `hadoop_namenode_security_enabled` is exported:
```
hadoop_namenode_security_enabled{kind="NameNodeStatus",role="Name …
```

feat(hadoop): Enable boolean metrics

---

trino/storage-connector/stackable/patches/451/0001-Add-CycloneDX-plugin.patch

The patch went missing during a merge in https://github.com/stackabletech/docker-images/pull/1095

fix(trino): Restore CycloneDX patch for 451

---

trino/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/1082.
Fixes tests that require the version in SQL queries (and likely the version being displayed in the web UI).
Reverts back to what @sbernauer had done in https://github.com/stackabletech/docker-images/pull/881

fix(trino): Reactivate the commitid plugin, otherwise tests fail

---

.github/ISSUE_TEMPLATE/early-pre-release.md
.github/ISSUE_TEMPLATE/update-base-java.md
.github/ISSUE_TEMPLATE/update-base-stackable.md
.github/ISSUE_TEMPLATE/update-base-ubi-rust-builders.md
.github/ISSUE_TEMPLATE/update-base-vector.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hbase-phoenix-omid.md
.github/ISSUE_TEMPLATE/update-product-hdfs.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-kafka.md
.github/ISSUE_TEMPLATE/update-product-nifi.md
.github/ISSUE_TEMPLATE/update-product-opa.md
.github/ISSUE_TEMPLATE/update-product-spark.md
.github/ISSUE_TEMPLATE/update-product-superset.md
.github/ISSUE_TEMPLATE/update-product-trino.md
.github/ISSUE_TEMPLATE/update-product-zookeeper.md
CHANGELOG.md
stackable-base/Dockerfile
stackable-devel/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/1162.
> [!CAUTION]
> Merging this will trigger a lot of builds across the images and consume all of the runners.
> [!NOTE]
<details>
```shell
``` …

chore(ubi-minimal): Update manifest SHA before SDP 25.7.0

---

.github/ISSUE_TEMPLATE/early-pre-release.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-superset.md
CHANGELOG.md
testing-tools/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/1066.
> [!NOTE]
<details>
```shell
```
</details>

chore(testing-tools): Update the base image

---

CHANGELOG.md
spark-k8s/Dockerfile
spark-k8s/stackable/jmx/config.yaml
spark-k8s/versions.py

This reverts commit b53fedfd579d5bc3bf0b59ca22ab73e037129bf1.
> [!NOTE]
<details>
```shell
```
</details>

fix: revert jmx exporter removal

---

CHANGELOG.md
opa/Dockerfile

Part of https://github.com/stackabletech/docker-images/issues/1068
This PR enables custom versions (with a suffix like `-stackable0.0.0-dev`) for OPA.
In the SBOM, the custom version is replaced by the original one (using `sed`), so vulnerabilities filed directly against OPA are still detected by scanners when scanning the SBOM.
I built OPA 1.4.2, tested it with the smoke test and manually validated that it reported the correct version.
> [!NOTE]
<details>
The image can be built and uploaded to the kind cluster with the …

feat: custom version for OPA

---

CHANGELOG.md
hadoop/stackable/patches/3.4.1/0006-HADOOP-19352.-Hadoop-OSS-Connector-adds-support-for-.patch
hadoop/stackable/patches/3.4.1/0007-HADOOP-19335.-Bump-netty-to-4.1.116-due-to-CVE-2024-.patch
hadoop/stackable/patches/3.4.1/0008-HADOOP-19465.-Upgrade-to-netty-4.1.118-due-to-CVE-20.patch
hadoop/stackable/patches/3.4.1/0009-HADOOP-19456.-Upgrade-kafka-to-3.9.0-to-fix-CVE-2024.patch
hadoop/stackable/patches/3.4.1/0010-HADOOP-19225.-Upgrade-Jetty-to-9.4.57.v20241219-due-.patch

Backported these patches to Hadoop 3.4.1 to get rid of a bunch of vulnerabilities:
- HADOOP-19352
- HADOOP-19335
- HADOOP-19465
- HADOOP-19456
- HADOOP-19225
They mainly just bump dependencies. The first one (Aliyun SDK bump) has some more changes related to the bump, but it's not a critical component as far as I see it (integration module for a chinese cloud provider's storage solution).
Build and smoke test were successfull. I also ran the HBase 2.6.2 smoke test with this Hadoop build, went fine as well.
> [!NOTE]
<details>
<summary>TIP: Running integration tests with a new product …

feat: backport Hadoop 3.4.1 vulnerability fixes

---

trino/trino/stackable/patches/470/0001-Add-CycloneDX-plugin.patch
trino/trino/stackable/patches/470/0002-Disable-web-ui-code-checking-because-flow-v0.241.0-f.patch
trino/trino/stackable/patches/476/0002-Disable-web-ui-code-checking-because-flow-v0.241.0-f.patch

The builds for Trino 470 and 476 [currently fail on ARM](https://github.com/stackabletech/docker-images/actions/runs/15720684576).
The reason is:
https://github.com/stackabletech/docker-images/pull/1168 switched the build command from `mvnw package` to `mvnw install`, so that `trino-storage-connector` can use our patched Trino libs. That causes the `verify` stage of Maven to execute as well, which for the affected Trino versions invokes [flow](https://github.com/facebook/flow) to check the Typescript code of the Web UI. This fails on ARM, because the non x86 binaries of flow 0.241.0 require glibc 2.35 (see https://github.com/facebook/flow/releases/tag/v0.238.3). UBI comes with glibc 2.34. As we can't bump glibc and I didn't want to use an older version of flow and flow wasn't even part of …

fix(trino): Disable checking of trino-web-ui

---

.github/workflows/mirror.yaml
.github/workflows/pr_pre-commit.yaml
.github/workflows/reusable_build_image.yaml
CHANGELOG.md

With `image-tools` 0.0.17 we now have a separate argument to provide the SDP version. This is needed because we want to include the architecture in the image tag (`0.0.0-dev-amd64`) but not in the `RELEASE` argument (that one should just be `0.0.0-dev` or `25.7.0`).
Before 0.0.17 the `--image-version` argument was used for both the image tag and the `RELEASE` arg.
This PR bumps the Github actions to use the new version of `image-tools` and provide the SDP version as a separate `--release` argument so `RELEASE` does not contain the architecture anymore.
See https://github.com/stackabletech/actions/pull/47 and https://github.com/stackabletech/image-tools/pull/55
Successful build with the new action: https://github.com/stackabletech/docker-images/actions/runs/15897788169/job/44833458187
I …

feat: update publish-image action to fix RELEASE arg

---

nifi/python/create_nifi_reporting_task.py

Follow up for https://github.com/stackabletech/docker-images/pull/1189.
Removed version flag, needs adjustment in nifi-operator.
> [!NOTE]
<details>
```shell
```
</details>

feat: remove version flag from NiFi 1 reporting task

---

testing-tools/Dockerfile

fix: image bloat due to https://github.com/moby/moby/issues/5419
This is now using the same useradd and groupadd commands as our other base images.

fix: image bloat due to https://github.com/moby/moby/issues/5419

---

CHANGELOG.md
stackable-base/Dockerfile
stackable-devel/Dockerfile
testing-tools/Dockerfile
ubi9-rust-builder/Dockerfile

Part of https://github.com/stackabletech/operator-templating/issues/512

chore: Bump UBI9-minimal base image, cargo-auditable and protoc

---

hadoop/Dockerfile
shared/checks/check-permissions-ownership.sh

fix: selectively copy items from hadoop-builder image to final image to not overwrite things from the base image
> [!NOTE]
<details>
```shell
```
</details>

fix: selectively copy items from hadoop-builder

---

CHANGELOG.md
conf.py

#1193 changed the UID to 1000, but the GID was set to 0. This caused issues, because the root group with ID 0 is already present. As such, the `groupadd` command fails which in turn breaks _all_ image builds.
**This PR set the GID to 1000 as well.**
Local test builds succeeded:
- stackable-base@1.0.0
- opa@1.4.2

fix: Change GID to 1000

---

hadoop/Dockerfile

They are needed for the downstream images (Druid, Hive, HBase, Spark, ...)
All of these built succesfully locally now.

fix: Add missing patched-libs

---

nifi/Dockerfile
testing-tools/python/requirements.txt

fix: Update nipyapi to 0.22.0 to work with custom nifi versions
The test still fails for me but for now unrelated reasons I'd say: https://github.com/stackabletech/nifi-operator/issues/814#issuecomment-3064125417

fix: Update nipyapi to 0.22.0 to work with custom nifi versions

---

CHANGELOG.md
hadoop/Dockerfile
hadoop/hadoop/Dockerfile
hadoop/hadoop/stackable/patches/3.3.6/0012-HADOOP-18583.-Fix-loading-of-OpenSSL-3.x-symbols-525.patch
hadoop/hadoop/stackable/patches/3.4.1/0011-HADOOP-18583.-Fix-loading-of-OpenSSL-3.x-symbols-525.patch

This was reported as SUP-215 internally.
This fixes 
* https://issues.apache.org/jira/browse/HADOOP-12845
* https://issues.apache.org/jira/browse/HADOOP-18583
Together they mean that the native library (OpenSSL) was not used for crypto work:
```
stackable@hdfs-namenode-default-0 /stackable/hadoop-3.4.0 $ hadoop checknative -a
2025-07-17 21:30:51,368 WARN  bzip2.Bzip2Factory (Bzip2Factory.java:isNativeBzip2Loaded(64)) - Failed to load/initialize native-bzip2 library system-native, will use pure-Java version
2025-07-17 21:30:51,371 INFO  zlib.ZlibFactory (ZlibFactory.java:loadNativeZLib(59)) - Successfully loaded & initialized native-zlib library
2025-07-17 21:30:51,371 WARN  erasurecode.ErasureCodeNative (ErasureCodeNative.java:<clinit>(55)) - ISA-L support is not available in your …
```

fix(hadoop): Backport HADOOP-18583 & fix OpenSSL native library

---

CHANGELOG.md
spark-k8s/stackable/patches/3.5.5/0002-Backport-SPARK-51311-BUILD-Promote-bcprov-jdk18on-to.patch
spark-k8s/stackable/patches/3.5.6/0002-Backport-SPARK-51311-BUILD-Promote-bcprov-jdk18on-to.patch

Hadoop has stopped exporting the bouncy castle dependency which leads to ClassNotFoundExceptions in kerberized environments.
Spark 4 has already fixed this issue in [SPARK-51311 ](https://github.com/apache/spark/pull/50077).
This PR backports the above to Spark 3.
The image contains the required jar file:
```
❯ docker run --rm oci.stackable.tech/sdp/spark-k8s:3.5.6-stackable0.0.0-dev find ./ -iname 'bcprov*'
...
./jars/bcprov-jdk18on-1.77.jar
```
> [!NOTE]
<details>
The image can be built and uploaded to the kind …

fix: spark 3 add bouncy castle as compile time dependency

---

stackable-devel/Dockerfile

> [!NOTE]
<details>
```shell
```
</details>

fix: install cyclonedx plugin using --locked

---

CHANGELOG.md
druid/Dockerfile
hadoop/Dockerfile
hadoop/hadoop/Dockerfile
hbase/hbase-opa-authorizer/Dockerfile
hbase/hbase-operator-tools/Dockerfile
hbase/hbase/Dockerfile
hbase/phoenix/Dockerfile
hive/Dockerfile
java-devel/Dockerfile
nifi/Dockerfile
omid/Dockerfile
spark-k8s/Dockerfile
trino/storage-connector/Dockerfile
trino/trino/Dockerfile
zookeeper/Dockerfile

/fixes https://github.com/stackabletech/docker-images/issues/1181
Maven as of 3.9+ supports an environment variable `MAVEN_ARGS` to standardise certain arguments to be used for every Maven invocation. This allows us to globally silence the transfer progress and enable batch mode and it allows us to remove the workarounds we had in place for Spark, Trino and NiFi.
I manually built all images and they succeeded. I did not run any integration tests or anything but I believe that once they built successfully it should be good.

Use custom Maven version for all our products

---

CHANGELOG.md
nifi/stackable/patches/2.4.0/0004-NIFI-14858-Make-SNI-checking-configurable.patch

This allows to manually work around https://github.com/stackabletech/nifi-operator/issues/812 by applying [NIFI-14848](https://issues.apache.org/jira/browse/NIFI-14858) to NiFi 2.4.0.
It allows disabling of SNI checks for NiFi 2.x
I did run the image build and we tested it manually on a cluster with an Ingress.
Without config overrides we'd get an error accessing NiFi.
With the config overrides it works:
```
nodes:
configOverrides:
nifi.properties:
nifi.web.https.sni.required: "false"
nifi.web.https.sni.host.check: "false"
```
> [!NOTE]
<details>
<summary>TIP: Running integration tests with a …

Backport NIFI-14858 to NiFi 2.4.0

---

.github/ISSUE_TEMPLATE/early-pre-release.md
.github/ISSUE_TEMPLATE/update-base-java.md
.github/ISSUE_TEMPLATE/update-base-stackable.md
.github/ISSUE_TEMPLATE/update-base-ubi-rust-builders.md
.github/ISSUE_TEMPLATE/update-base-vector.md
.github/ISSUE_TEMPLATE/update-product-airflow.md
.github/ISSUE_TEMPLATE/update-product-druid.md
.github/ISSUE_TEMPLATE/update-product-hbase-phoenix-omid.md
.github/ISSUE_TEMPLATE/update-product-hdfs.md
.github/ISSUE_TEMPLATE/update-product-hive.md
.github/ISSUE_TEMPLATE/update-product-kafka.md
.github/ISSUE_TEMPLATE/update-product-nifi.md
.github/ISSUE_TEMPLATE/update-product-opa.md
.github/ISSUE_TEMPLATE/update-product-opensearch.md
.github/ISSUE_TEMPLATE/update-product-spark.md
.github/ISSUE_TEMPLATE/update-product-superset.md
.github/ISSUE_TEMPLATE/update-product-trino.md
.github/ISSUE_TEMPLATE/update-product-zookeeper.md

This PR slightly tweaks the issue templates while using them for the upcoming SDP 25.11.0 release.

chore: Update issue templates pre 25.11.0

---

airflow/opa-auth-manager/airflow-2/pyproject.toml
airflow/opa-auth-manager/airflow-2/uv.lock

Fixes Airflow 2 image builds: https://github.com/stackabletech/docker-images/actions/runs/17732572125/job/50386763611#step:4:1733
:green_circle: Build:
```
❯ uv run pytest --disable-warnings
Using CPython 3.12.10
Creating virtual environment at: .venv
Built opa-auth-manager @ file:///home/razvan/repo/stackable/docker-images/airflow/opa-auth-manager/airflow-2
Installed 148 packages in 101ms
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.12.10, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/razvan/repo/stackable/docker-images/airflow/opa-auth-manager/airflow-2
configfile: pyproject.toml
plugins: anyio-4.10.0
collected 19 items …
```

airflow 2: pin flask-limiter version for opa manager tests

---

spark-k8s/Dockerfile

fix(spark-k8s): Use correct release and Python ARGs

---

.github/ISSUE_TEMPLATE/update-base-vector.md
CHANGELOG.md
airflow/boil-config.toml
java-base/boil-config.toml
jdk-base/boil-config.toml
opa/boil-config.toml
spark-k8s/boil-config.toml
superset/boil-config.toml
vector/boil-config.toml

Part of https://github.com/stackabletech/docker-images/issues/1233
> [!NOTE]
<details>
```shell
```
</details>

chore(vector): Update image for 25.11.0

---

rust/boil/src/build/bakefile.rs
rust/boil/src/build/cli.rs
rust/boil/src/utils.rs

@siegfriedweber recently found out that it is currently not possible to specify a port for the registry host. This PR adds support for this.
Tested with
```shell
cargo boil build opa=1.4.2 --registry localhost:8080
Successfully built 1 image:
localhost:8080/sdp/opa:1.4.2-stackable0.0.0-dev-amd64
```

feat(boil): Add support for port in registry host

---

.github/workflows/boil_pr.yaml
.github/workflows/boil_release.yaml
.yamllint.yaml

This PR clearly separates the PR and release workflows for `boil`. This is done because previously, the cargo-deny checks could have failed the release workflow (which is triggered by a Git tag). This would result in the need to move Git tags, which should be avoided in all circumstances.

ci(boil): Improve and split workflows

---

.scripts/upload_new_keycloak_version.sh
CHANGELOG.md
testing-tools/Dockerfile
testing-tools/README.md
testing-tools/boil-config.toml

Part of https://github.com/stackabletech/docker-images/issues/1232
Ran tests with `hdfs-operator` integrationtests and `opa-operator` integrationtest using `testing-tools`
```
--- PASS: kuttl (3574.94s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_hadoop-3.4.1_zookeeper-3.9.3_zookeeper-latest-3.9.3_number-of-datanodes-2_datanode-pvcs-default_listener-class-external-unstable_openshift-false (267.23s)
--- PASS: kuttl/harness/topology-provider_hadoop-latest-3.4.1_zookeeper-latest-3.9.3_krb5-1.21.1_kerberos-backend-mit_openshift-false (405.85s)
--- PASS: kuttl/harness/smoke_hadoop-3.4.1_zookeeper-3.9.3_zookeeper-latest-3.9.3_number-of-datanodes-1_datanode-pvcs-default_listener-class-external-unstable_openshift-false (194.53s)
--- PASS: …
```

chore(testing-tools): Update image for 25.11.0
